#ifndef __AAFResult_h_
#define __AAFResult_h_

/******************************************\
*                                          *
* Advanced Authoring Format                *
*                                          *
* Copyright (c) 1998 Avid Technology, Inc. *
* Copyright (c) 1998 Microsoft Corporation *
*                                          *
\******************************************/


/* SESSION/FILE Error Codes */
#define AAFRESULT_BAD_SESSION				 16
#define AAFRESULT_BADSESSIONOPEN			 17
#define AAFRESULT_BADSESSIONMETA			 18
#define AAFRESULT_BADSESSIONCLOSE			 19
#define AAFRESULT_BADCONTAINER				 20
#define AAFRESULT_FILEREV_NOT_SUPP			 21
#define AAFRESULT_FILEREV_DIFF				 22
#define AAFRESULT_BADOPEN					 23
#define AAFRESULT_BADCLOSE					 24
#define AAFRESULT_BAD_FHDL					 25
#define AAFRESULT_BADHEAD					 26
#define AAFRESULT_NOBYTEORDER				 27
#define AAFRESULT_INVALID_BYTEORDER			 28
#define AAFRESULT_NOTAAFFILE				 29
#define AAFRESULT_WRONG_FILETYPE			 30
#define AAFRESULT_WRONG_OPENMODE			 31
#define AAFRESULT_CONTAINERWRITE			 32
#define AAFRESULT_FILE_NOT_FOUND			 33
#define AAFRESULT_CANNOT_SAVE_CLSD			 34
#define AAFRESULT_CANNOT_LOAD_CLSD			 35
#define AAFRESULT_FILE_REV_200				 36
#define AAFRESULT_NEED_PRODUCT_IDENT		 37
#define AAFRESULT_NOT_WRITEABLE				 38
#define AAFRESULT_NOT_READABLE				 39
#define AAFRESULT_FILE_EXISTS				 40

/* MEDIA Error Codes */
#define AAFRESULT_DESCSAMPRATE				100
#define AAFRESULT_SOURCEMOBLIST				101
#define AAFRESULT_DESCLENGTH				102
#define AAFRESULT_INTERNAL_MDO				103
#define AAFRESULT_3COMPONENT				104
#define AAFRESULT_INTERNAL_CORRUPTVINFO 	105
#define AAFRESULT_BADSAMPLEOFFSET			106
#define AAFRESULT_ONESAMPLEREAD				107
#define AAFRESULT_ONESAMPLEWRITE			108
#define AAFRESULT_DECOMPRESS				109
#define AAFRESULT_NODATA					110
#define AAFRESULT_SMALLBUF					111
#define AAFRESULT_BADCOMPR					112
#define AAFRESULT_BADPIXFORM				113
#define AAFRESULT_BADLAYOUT					114
#define AAFRESULT_COMPRLINESWR				115
#define AAFRESULT_COMPRLINESRD				116
#define AAFRESULT_BADMEDIATYPE 				117
#define AAFRESULT_BADDATAADDRESS			118
#define AAFRESULT_BAD_MDHDL					119
#define AAFRESULT_MEDIA_NOT_FOUND			120
#define AAFRESULT_ILLEGAL_MEMFMT			121
#define AAFRESULT_ILLEGAL_FILEFMT			122
#define AAFRESULT_SWABBUFSIZE				123
#define AAFRESULT_MISSING_SWAP_PROC			124
#define AAFRESULT_NULL_STREAMPROC			125
#define AAFRESULT_NULLBUF					126
#define AAFRESULT_SWAP_SETUP				127
#define AAFRESULT_INVALID_FILE_MOB			128
#define AAFRESULT_SINGLE_CHANNEL_OP			129
#define AAFRESULT_INVALID_CACHE_SIZE		130
#define AAFRESULT_NOT_FILEMOB				131
#define AAFRESULT_TRANSLATE_SAMPLE_SIZE		132
#define AAFRESULT_TRANSLATE_NON_INTEGRAL_RATE 133
#define AAFRESULT_MISSING_MEDIA_REP			134
#define AAFRESULT_NOT_LONGWORD				135
#define AAFRESULT_XFER_DUPCH				136
#define AAFRESULT_MEDIA_NOT_INIT			137
#define AAFRESULT_BLOCKING_SIZE				138
#define AAFRESULT_WRONG_MEDIATYPE 			139
#define AAFRESULT_MULTI_WRITELEN			140
#define AAFRESULT_STREAM_REOPEN				141
#define AAFRESULT_TOO_MANY_FMT_OPS 			142
#define AAFRESULT_MEDIASTREAM_NOTALLOWED	143
#define AAFRESULT_STILLFRAME_BADLENGTH		144
#define AAFRESULT_DATA_NONCONTIG			145
#define AAFRESULT_OPLIST_OVERFLOW			146
#define AAFRESULT_STREAM_CLOSED 			147
#define AAF_RESULT_USE_MULTI_CREATE			148
#define AAFRESULT_MEDIA_OPENMODE			149
#define AAFRESULT_MEDIA_CANNOT_CLOSE 		150
#define AAFRESULT_CODEC_INVALID 			151
#define AAFRESULT_INVALID_OP_CODEC 			152
#define AAFRESULT_BAD_CODEC_REV  			153
#define AAFRESULT_CODEC_CHANNELS 			154
#define AAFRESULT_INTERN_TOO_SMALL  		155
#define AAFRESULT_INTERNAL_UNKNOWN_LOC 		156
#define AAFRESULT_TRANSLATE 				157
#define AAFRESULT_EOF 						158
#define AAFRESULT_TIFFVERSION 				159
#define AAFRESULT_BADTIFFCOUNT 				160
#define AAFRESULT_24BITVIDEO 				161
#define AAFRESULT_JPEGBASELINE 				162
#define AAFRESULT_BADJPEGINFO 				163
#define AAFRESULT_BADQTABLE  				164
#define AAFRESULT_BADACTABLE 				165
#define AAFRESULT_BADDCTABLE 				166
#define AAFRESULT_NOFRAMEINDEX  			167
#define AAFRESULT_BADFRAMEOFFSET 			168
#define AAFRESULT_JPEGPCM 					169
#define AAFRESULT_JPEGDISABLED 				170
#define AAFRESULT_JPEGPROBLEM 				171
#define AAFRESULT_BADEXPORTPIXFORM 			172
#define AAFRESULT_BADEXPORTLAYOUT 			173
#define AAFRESULT_BADRWLINES 				174
#define AAFRESULT_BADAIFCDATA 				175
#define AAFRESULT_BADWAVEDATA  				176
#define AAFRESULT_NOAUDIOCONV 				177
#define AAFRESULT_XFER_NOT_BYTES 			178
#define AAFRESULT_CODEC_NAME_SIZE 			179
#define AAFRESULT_ZERO_SAMPLESIZE 			180
#define AAFRESULT_ZERO_PIXELSIZE 			181
#define AAFRESULT_BAD_VARIETY 				182
	
/* OBJECT Error Codes */
#define AAFRESULT_NULLOBJECT				200
#define AAFRESULT_BADINDEX					201
#define AAFRESULT_INVALID_LINKAGE			202
#define AAFRESULT_BAD_PROP					203
#define AAFRESULT_BAD_TYPE					204
#define AAFRESULT_SWAB						205
#define AAFRESULT_END_OF_DATA 				206
#define AAFRESULT_PROP_NOT_PRESENT			207
#define AAFRESULT_INVALID_DATAKIND			208
#define AAFRESULT_DATAKIND_EXIST			209
#define AAFRESULT_TOO_MANY_TYPES			210
	
/* MOB Error Codes */
#define AAFRESULT_NOT_SOURCE_CLIP			250
#define AAFRESULT_FILL_FOUND				251
#define AAFRESULT_BAD_LENGTH 				252
#define AAFRESULT_BADRATE					253
#define AAFRESULT_INVALID_ROUNDING			254
#define AAFRESULT_TIMECODE_NOT_FOUND		255
#define AAFRESULT_NO_TIMECODE				256
#define AAFRESULT_INVALID_TIMECODE 			257
#define AAFRESULT_TRACK_NOT_FOUND			258
#define AAFRESULT_BAD_SLOTLENGTH			259
#define AAFRESULT_MISSING_TRACKID 			260
#define AAFRESULT_TRACK_EXISTS 				261
#define AAFRESULT_MOB_NOT_FOUND 			262
#define AAFRESULT_NO_MORE_MOBS 				263
#define AAFRESULT_DUPLICATE_MOBID 			264
#define AAFRESULT_MISSING_MOBID 			265
#define AAFRESULT_EFFECTDEF_EXIST  			266
#define AAFRESULT_INVALID_EFFECTDEF 		267
#define AAFRESULT_INVALID_EFFECT 			268
#define AAFRESULT_INVALID_EFFECTARG  		269
#define AAFRESULT_INVALID_CVAL 				270
#define AAFRESULT_RENDER_NOT_FOUND 			271
#define AAFRESULT_BAD_ITHDL 				272
#define AAFRESULT_NO_MORE_OBJECTS 			273
#define AAFRESULT_ITER_WRONG_TYPE 			274
#define AAFRESULT_INVALID_SEARCH_CRIT 		275	
#define AAFRESULT_INTERNAL_ITERATOR 		276
#define AAFRESULT_NULL_MATCHFUNC 			277
#define AAFRESULT_NULL_CALLBACKFUNC 		278
#define AAFRESULT_TRAVERSAL_NOT_POSS 		279
#define AAFRESULT_INVALID_TRAN_EFFECT		280
#define AAFRESULT_ADJACENT_TRAN  			281
#define AAFRESULT_LEADING_TRAN  			282
#define AAFRESULT_INSUFF_TRAN_MATERIAL  	283
#define AAFRESULT_PULLDOWN_DIRECTION  		284
#define AAFRESULT_PULLDOWN_FUNC  			285
#define AAFRESULT_PULLDOWN_KIND  			286
#define AAFRESULT_BAD_SRCH_ITER  			287
#define AAFRESULT_NOT_COMPOSITION  			288
#define AAFRESULT_NOT_A_TRACK  				289
#define AAFRESULT_PARSE_EFFECT_AMBIGUOUS  	290

/* SIMPLE COMPOSITION Error Codes */
#define AAFRESULT_BAD_STRACKHDL				300
#define AAFRESULT_STRACK_APPEND_ILLEGAL		301

/* GENERIC Error Codes ***/
#define AAFRESULT_NOMEMORY					350
#define AAFRESULT_OFFSET_SIZE				351
#define AAFRESULT_INTERNAL_NEG64			352
#define AAFRESULT_OVERFLOW64				353
#define AAFRESULT_NOT_IN_15					353
#define AAFRESULT_NOT_IN_20 				354
#define AAFRESULT_NULL_PARAM				355
#define AAFRESULT_ZERO_DIVIDE				356

/* SEMANTIC CHECKING Error Codes */
#define AAFRESULT_REQUIRED_POSITIVE			400
#define AAFRESULT_INVALID_TRACKKIND			401
#define AAFRESULT_INVALID_EDGETYPE			402
#define AAFRESULT_INVALID_FILMTYPE			403
#define AAFRESULT_INVALID_MOBTYPE 			404
#define AAFRESULT_INVALID_TAPECASETYPE		405
#define AAFRESULT_INVALID_VIDEOSIGNALTYPE 	406
#define AAFRESULT_INVALID_TAPEFORMATTYPE	407
#define AAFRESULT_INVALID_EDITHINT 			408
#define AAFRESULT_INVALID_INTERPKIND		409
#define AAFRESULT_INVALID_TRACK_REF			410
#define AAFRESULT_INVALID_OBJ				411
#define AAFRESULT_BAD_VIRTUAL_CREATE 		412
#define AAFRESULT_INVALID_CLASS_ID			413
#define AAFRESULT_OBJECT_SEMANTIC			414
#define AAFRESULT_DATA_IN_SEMANTIC			415
#define AAFRESULT_DATA_OUT_SEMANTIC			416
#define AAFRESULT_TYPE_SEMANTIC 			417
#define AAFRESULT_INVALID_ATTRIBUTEKIND		418
#define AAFRESULT_DATA_MDES_DISAGREE		419
#define AAFRESULT_CODEC_SEMANTIC_WARN		420
#define AAFRESULT_INVALID_BOOLTYPE			421

/* INTERNAL Error Codes */
#define AAFRESULT_TABLE_DUP_KEY				450
#define AAFRESULT_TABLE_MISSING_COMPARE		451
#define AAFRESULT_TABLE_BAD_HDL				452
#define AAFRESULT_TABLE_BAD_ITER			453
#define AAFRESULT_BENTO_PROBLEM				454
#define AAFRESULT_BENTO_HANDLER				455
#define AAFRESULT_PROPID_MATCH				456
#define AAFRESULT_INTERNAL_DIVIDE			457

/* Testing Error Codes */
#define AAFRESULT_TEST_FAILED				500

#define AAFRESULT_MAXCODE					501


#endif // ! __AAFResult_h_
