############################################
#                                          #
# Advanced Authoring Format                #
#                                          #
# Copyright (c) 1998 Avid Technology, Inc. #
#                                          #
############################################

#
# Contains elements for doing makedepend
#
# Requires that DEPEND_INCLUDES and SOURCES be already defined.
#

basedepend:
	rm -f .depend.mk${PTFM_SUFX}
	touch .depend.mk${PTFM_SUFX}
	makedepend -f.depend.mk${PTFM_SUFX} $(OBJFILE) ${DEPEND_INCLUDES} ${SOURCES}


#
# Dependencies (this file generated by basedepend: target).  Only
# include if it exists...
#
ifneq (, $(wildcard .depend.mk${PTFM_SUFX}))
include ./.depend.mk${PTFM_SUFX}
endif
