
.PHONY : all
all : aafomf

.PHONY : aafomf
aafomf:
	cd AafOmf && $(MAKE)

.PHONY : clean
clean :
	cd AafOmf && $(MAKE) GENDEPS=0 $@

.PHONY : realclean
realclean :
	cd AafOmf && $(MAKE) GENDEPS=0 $@

