#!/bin/sh
export LD_LIBRARY_PATH=../lib:./lib:$LD_LIBRARY_PATH
/usr/java/j2sdk1.4.1_02/bin/java -cp ../lib/zvtm.jar:../lib/aafviewer.jar:../lib/xercesImpl.jar:../lib/xmlParserAPIs.jar bbc.rd.aaf.aafviewer.AAFViewer
