
.PHONY : all
all : ComModTestAAF CreateSequence EssenceAccess

.PHONY : ComModTestAAF
ComModTestAAF :
	cd ComModTestAAF && $(MAKE)

.PHONY : CreateSequence
CreateSequence :
	cd CreateSequence && $(MAKE)

.PHONY : EssenceAccess
EssenceAccess :
	cd EssenceAccess && $(MAKE)