#c /******************************************\
#c *                                          *
#c * Advanced Authoring Format                *
#c *                                          *
#c * Copyright (c) 1998 Avid Technology, Inc. *
#c * Copyright (c) 1998 Microsoft Corporation *
#c *                                          *
#c \******************************************/



#ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
#c
#c AutoDodo macro file for use in generating COM API implementation
#c header files.
#c
#ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc


#import macros/base.mac


#ccccccccccccccccccccccccccc
#c
#c Includes another file.
#c
#c Argument: Base filename
#c
#startm AD_INCLUDE 01
#ifndef __%01_h__
#include "%01.h"
#endif
#endm


#ccccccccccccccccccccccccccc
#c
#c Goes at the head of the file.
#c
#c Arguments: none
#c
#startm AD_HEAD 00
//@doc
//@class    .this-module | Implementation class for .this-module
#ifndef __C.this-module_h__
#define __C.this-module_h__

#ifndef __.this-module_h__
#include ".this-module.h"
#endif
#endm


#ccccccccccccccccccccccccccc
#c
#c AAFTypes support for IDL
#c
#c Arguments: none
#c
#startm AD_TYPES_HEAD 00
#endm


#ccccccccccccccccccccccccccc
#c
#c Starts a class definition
#c
#c Arguments: none
#c
#startm AD_CLASS_BEGIN 00
#ifndef __C.parent-module_h__
#include "C.parent-module.h"
#endif

//
// Forward declaration
//
class Impl.this-module;


class C.this-module
  : public I.this-module,
    public C.parent-module
{
  //
  // Constructor/destructor
  //
  C.this-module (IUnknown * pControllingUnknown, aafBool doInit = AAFTrue);
  ~C.this-module ();

  //********
#endm


#ccccccccccccccccccccccccccc
#c
#c Starts a class definition with no parent class
#c
#c Arguments: none
#c
#startm AD_ROOT_CLASS_BEGIN 00
#ifndef __CAAFUnknown_h__
#include "CAAFUnknown.h"
#endif

//
// Forward declaration
//
class Impl.this-module;


class C.this-module
  : public I.this-module,
    public CAAFUnknown
{
public:
  //
  // Constructor/destructor
  //
  C.this-module (IUnknown * pControllingUnknown, aafBool doInit = AAFTrue);
  virtual ~C.this-module ();

  //********
#endm



#ccccccccccccccccccccccccccc
#c
#c Types definitions should only be used by idl and c++ & impl headers
#c 
#c
#c GUID
#c Argument01: hex long  0-3[leading 0's w/o leading 0x]
#c Argument02: hex short 4-5[leading 0's w/o leading 0x]
#c Argument03: hex short 6-7[leading 0's w/o leading 0x]
#c Argument04: hex byte   8 [leading 0's w/o leading 0x]
#c Argument05: hex byte   9 [leading 0's w/o leading 0x]
#c Argument06: hex byte  10 [leading 0's w/o leading 0x]
#c Argument07: hex byte  11 [leading 0's w/o leading 0x]
#c Argument08: hex byte  12 [leading 0's w/o leading 0x]
#c Argument09: hex byte  13 [leading 0's w/o leading 0x]
#c Argument10: hex byte  14 [leading 0's w/o leading 0x]
#c Argument11: hex byte  15 [leading 0's w/o leading 0x]
#c
#c Example:
#c AD_TYPES_BEGIN(b1a21372, 1a7d, 11d2, bf, 78, 00, 10, 4b, c9, 15, 6d)
#c
#c TomR:980716: Added
#c
#startm AD_TYPES_BEGIN 11
#endm


#ccccccccccccccccccccccccccc
#c
#c Ends a types definition
#c
#c Types definitions should only be used by idl and c++ & impl headers
#c
#c Arguments: none
#c
#startm AD_TYPES_END 00
#endif // ! __C.this-module_h__
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a method which takes no arguments.
#c
#c Argument1: method name
#c Argument2: method description
#c
#startm AD_METHOD0 02
  // %02
  STDMETHOD (%01)
     ();
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a method which takes one argument.
#c
#c Macro Arg 01: method name
#c
#c Macro arguments 02+:
#c 
#c meth arg #   arg modfrs   obj style   type    name    arg cmnt
#c ----------   ----------   ---------   ----    ----    --------
#c metharg 1    02           03          04      05      06
#c
#c Macro Arg 07: method description
#c
#startm AD_XMETHOD1 07
  // %07
  STDMETHOD (%01)
    (/*%02*/ .%03-adornment%04 .%03-indirection %05); // %06 \
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a method which takes two arguments.
#c
#c Macro Arg 01: method name
#c
#c Macro arguments 02+:
#c 
#c meth arg #   arg modfrs   obj style   type    name    arg cmnt
#c ----------   ----------   ---------   ----    ----    --------
#c metharg 1    02           03          04      05      06
#c metharg 2    07           08          09      10      11
#c
#c Macro Arg 12: method description
#c
#startm AD_XMETHOD2 12
  // %12
  STDMETHOD (%01)
    (/*%02*/ .%03-adornment%04 .%03-indirection %05, // %06
	 /*%07*/ .%08-adornment%09 .%08-indirection %10); // %11 \
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a method which takes three arguments.
#c
#c Macro Arg 01: method name
#c
#c Macro arguments 02+:
#c 
#c meth arg #   arg modfrs   obj style   type    name    arg cmnt
#c ----------   ----------   ---------   ----    ----    --------
#c metharg 1    02           03          04      05      06
#c metharg 2    07           08          09      10      11
#c metharg 3    12           13          14      15      16
#c
#c Macro Arg 17: method description
#c
#startm AD_XMETHOD3 17
  // %17
  STDMETHOD (%01)
    (/*%02*/ .%03-adornment%04 .%03-indirection %05, // %06
	 /*%07*/ .%08-adornment%09 .%08-indirection %10, // %11
	 /*%12*/ .%13-adornment%14 .%13-indirection %15); // %16 \
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a method which takes four arguments.
#c
#c Macro Arg 01: method name
#c
#c Macro arguments 02+:
#c 
#c meth arg #   arg modfrs   obj style   type    name    arg cmnt
#c ----------   ----------   ---------   ----    ----    --------
#c metharg 1    02           03          04      05      06
#c metharg 2    07           08          09      10      11
#c metharg 3    12           13          14      15      16
#c metharg 4    17           18          19      20      21
#c
#c Macro Arg 22: method description
#c
#startm AD_XMETHOD4 22
  // %22
  STDMETHOD (%01)
    (/*%02*/ .%03-adornment%04 .%03-indirection %05, // %06
	 /*%07*/ .%08-adornment%09 .%08-indirection %10, // %11
	 /*%12*/ .%13-adornment%14 .%13-indirection %15, // %16
	 /*%17*/ .%18-adornment%19 .%18-indirection %20); // %21 \
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a method which takes five arguments.
#c
#c Macro Arg 01: method name
#c
#c Macro arguments 02+:
#c 
#c meth arg #   arg modfrs   obj style   type    name    arg cmnt
#c ----------   ----------   ---------   ----    ----    --------
#c metharg 1    02           03          04      05      06
#c metharg 2    07           08          09      10      11
#c metharg 3    12           13          14      15      16
#c metharg 4    17           18          19      20      21
#c metharg 5    22           23          24      25      26
#c
#c Macro Arg 27: method description
#c
#startm AD_XMETHOD5 27
  // %27
  STDMETHOD (%01)
    (/*%02*/ .%03-adornment%04 .%03-indirection %05, // %06
	 /*%07*/ .%08-adornment%09 .%08-indirection %10, // %11
	 /*%12*/ .%13-adornment%14 .%13-indirection %15, // %16
	 /*%17*/ .%18-adornment%19 .%18-indirection %20, // %21
	 /*%22*/ .%23-adornment%24 .%23-indirection %25); // %26 \
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a method which takes six arguments.
#c
#c Macro Arg 01: method name
#c
#c Macro arguments 02+:
#c 
#c meth arg #   arg modfrs   obj style   type    name    arg cmnt
#c ----------   ----------   ---------   ----    ----    --------
#c metharg 1    02           03          04      05      06
#c metharg 2    07           08          09      10      11
#c metharg 3    12           13          14      15      16
#c metharg 4    17           18          19      20      21
#c metharg 5    22           23          24      25      26
#c metharg 6    27           28          29      30      31
#c
#c Macro Arg 32: method description
#c
#startm AD_XMETHOD6 32
  // %32
  STDMETHOD (%01)
    (/*%02*/ .%03-adornment%04 .%03-indirection %05, // %06
	 /*%07*/ .%08-adornment%09 .%08-indirection %10, // %11
	 /*%12*/ .%13-adornment%14 .%13-indirection %15, // %16
	 /*%17*/ .%18-adornment%19 .%18-indirection %20, // %21
	 /*%22*/ .%23-adornment%24 .%23-indirection %25, // %26
	 /*%27*/ .%28-adornment%29 .%28-indirection %30); // %31 \
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a method which takes seven arguments.
#c
#c Macro Arg 01: method name
#c
#c Macro arguments 02+:
#c 
#c meth arg #   arg modfrs   obj style   type    name    arg cmnt
#c ----------   ----------   ---------   ----    ----    --------
#c metharg 1    02           03          04      05      06
#c metharg 2    07           08          09      10      11
#c metharg 3    12           13          14      15      16
#c metharg 4    17           18          19      20      21
#c metharg 5    22           23          24      25      26
#c metharg 6    27           28          29      30      31
#c metharg 7    32           33          34      35      36
#c
#c Macro Arg 37: method description
#c
#startm AD_XMETHOD7 37
  // %37
  STDMETHOD (%01)
    (/*%02*/ .%03-adornment%04 .%03-indirection %05, // %06
	 /*%07*/ .%08-adornment%09 .%08-indirection %10, // %11
	 /*%12*/ .%13-adornment%14 .%13-indirection %15, // %16
	 /*%17*/ .%18-adornment%19 .%18-indirection %20, // %21
	 /*%22*/ .%23-adornment%24 .%23-indirection %25, // %26
	 /*%27*/ .%28-adornment%29 .%28-indirection %30, // %31
	 /*%32*/ .%33-adornment%34 .%33-indirection %35); // %36 \
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a method which takes eight arguments.
#c
#c Macro Arg 01: method name
#c
#c Macro arguments 02+:
#c 
#c meth arg #   arg modfrs   obj style   type    name    arg cmnt
#c ----------   ----------   ---------   ----    ----    --------
#c metharg 1    02           03          04      05      06
#c metharg 2    07           08          09      10      11
#c metharg 3    12           13          14      15      16
#c metharg 4    17           18          19      20      21
#c metharg 5    22           23          24      25      26
#c metharg 6    27           28          29      30      31
#c metharg 7    32           33          34      35      36
#c metharg 8    37           38          39      40      41
#c
#c Macro Arg 42: method description
#c
#startm AD_XMETHOD8 42
  // %42
  STDMETHOD (%01)
    (/*%02*/ .%03-adornment%04 .%03-indirection %05, // %06
	 /*%07*/ .%08-adornment%09 .%08-indirection %10, // %11
	 /*%12*/ .%13-adornment%14 .%13-indirection %15, // %16
	 /*%17*/ .%18-adornment%19 .%18-indirection %20, // %21
	 /*%22*/ .%23-adornment%24 .%23-indirection %25, // %26
	 /*%27*/ .%28-adornment%29 .%28-indirection %30, // %31
	 /*%32*/ .%33-adornment%34 .%33-indirection %35, // %36
	 /*%37*/ .%38-adornment%39 .%38-indirection %40); // %41 \
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a method which takes nine arguments.
#c
#c Macro Arg 01: method name
#c
#c Macro arguments 02+:
#c 
#c meth arg #   arg modfrs   obj style   type    name    arg cmnt
#c ----------   ----------   ---------   ----    ----    --------
#c metharg 1    02           03          04      05      06
#c metharg 2    07           08          09      10      11
#c metharg 3    12           13          14      15      16
#c metharg 4    17           18          19      20      21
#c metharg 5    22           23          24      25      26
#c metharg 6    27           28          29      30      31
#c metharg 7    32           33          34      35      36
#c metharg 8    37           38          39      40      41
#c metharg 9    42           43          44      45      46
#c
#c Macro Arg 47: method description
#c
#startm AD_XMETHOD9 47
  // %47
  STDMETHOD (%01)
    (/*%02*/ .%03-adornment%04 .%03-indirection %05, // %06
	 /*%07*/ .%08-adornment%09 .%08-indirection %10, // %11
	 /*%12*/ .%13-adornment%14 .%13-indirection %15, // %16
	 /*%17*/ .%18-adornment%19 .%18-indirection %20, // %21
	 /*%22*/ .%23-adornment%24 .%23-indirection %25, // %26
	 /*%27*/ .%28-adornment%29 .%28-indirection %30, // %31
	 /*%32*/ .%33-adornment%34 .%33-indirection %35, // %36
	 /*%37*/ .%38-adornment%39 .%38-indirection %40, // %41
	 /*%42*/ .%43-adornment%44 .%43-indirection %45); // %46 \
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a method which takes ten arguments.
#c
#c Macro Arg 01: method name
#c
#c Macro arguments 02+:
#c 
#c meth arg #   arg modfrs   obj style   type    name    arg cmnt
#c ----------   ----------   ---------   ----    ----    --------
#c metharg 1    02           03          04      05      06
#c metharg 2    07           08          09      10      11
#c metharg 3    12           13          14      15      16
#c metharg 4    17           18          19      20      21
#c metharg 5    22           23          24      25      26
#c metharg 6    27           28          29      30      31
#c metharg 7    32           33          34      35      36
#c metharg 8    37           38          39      40      41
#c metharg 9    42           43          44      45      46
#c metharg 10   47           48          49      50      51
#c
#c Macro Arg 52: method description
#c
#startm AD_XMETHOD_10 52
  // %52
  STDMETHOD (%01)
    (/*%02*/ .%03-adornment%04 .%03-indirection %05, // %06
	 /*%07*/ .%08-adornment%09 .%08-indirection %10, // %11
	 /*%12*/ .%13-adornment%14 .%13-indirection %15, // %16
	 /*%17*/ .%18-adornment%19 .%18-indirection %20, // %21
	 /*%22*/ .%23-adornment%24 .%23-indirection %25, // %26
	 /*%27*/ .%28-adornment%29 .%28-indirection %30, // %31
	 /*%32*/ .%33-adornment%34 .%33-indirection %35, // %36
	 /*%37*/ .%38-adornment%39 .%38-indirection %40, // %41
	 /*%42*/ .%43-adornment%44 .%43-indirection %45, // %46
	 /*%47*/ .%48-adornment%49 .%48-indirection %50); // %51 \
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a method which takes eleven arguments.
#c
#c Macro Arg 01: method name
#c
#c Macro arguments 02+:
#c 
#c meth arg #   arg modfrs   obj style   type    name    arg cmnt
#c ----------   ----------   ---------   ----    ----    --------
#c metharg 1    02           03          04      05      06
#c metharg 2    07           08          09      10      11
#c metharg 3    12           13          14      15      16
#c metharg 4    17           18          19      20      21
#c metharg 5    22           23          24      25      26
#c metharg 6    27           28          29      30      31
#c metharg 7    32           33          34      35      36
#c metharg 8    37           38          39      40      41
#c metharg 9    42           43          44      45      46
#c metharg 10   47           48          49      50      51
#c metharg 11   52           53          54      55      56
#c
#c Macro Arg 57: method description
#c
#startm AD_XMETHOD_11 57
  // %57
  STDMETHOD (%01)
    (/*%02*/ .%03-adornment%04 .%03-indirection %05, // %06
	 /*%07*/ .%08-adornment%09 .%08-indirection %10, // %11
	 /*%12*/ .%13-adornment%14 .%13-indirection %15, // %16
	 /*%17*/ .%18-adornment%19 .%18-indirection %20, // %21
	 /*%22*/ .%23-adornment%24 .%23-indirection %25, // %26
	 /*%27*/ .%28-adornment%29 .%28-indirection %30, // %31
	 /*%32*/ .%33-adornment%34 .%33-indirection %35, // %36
	 /*%37*/ .%38-adornment%39 .%38-indirection %40, // %41
	 /*%42*/ .%43-adornment%44 .%43-indirection %45, // %46
	 /*%47*/ .%48-adornment%49 .%48-indirection %50, // %51
	 /*%52*/ .%53-adornment%54 .%53-indirection %55); // %56 \
#endm


#ccccccccccccccccccccccccccc
#c
#c Ends a class definition
#c
#c Arguments: none
#c
#startm AD_CLASS_END 00
  // 
  // Declare the QI that implements for the interfaces
  // for this module. This will be called by CAAFUnknown::QueryInterface().
  // 
  virtual HRESULT InternalQueryInterface(REFIID riid, void **ppvObjOut);


public:
  //
  // This class as concrete. All AAF objects can be constructed from
  // a CLSID. This will allow subclassing all "base-classes" by
  // aggreggation.
  // 
  AAF_DECLARE_CONCRETE();
  //
  //********

  // Declare the module test method. The implementation of the will be be
  // in /test/C.this-moduleTest.cpp.
  static HRESULT test();

  //
  // Return private implementation pointer for delegation.
  // NOTE: This is NOT the pointer to the COM object's implementation
  // object!
  STDMETHOD(GetImplRep)(/*[retval, string, out]*/ unsigned char **);
};

#endif // ! __C.this-module_h__
#endm


#ccccccccccccccccccccccccccc
#c
#c Ends a class definition for AAFObject
#c
#c Arguments: none
#c
#startm AD_ROOT_CLASS_END 00

protected:
  // 
  // Declare the QI that implements for the interfaces
  // for this module. This will be called by CAAFUnknown::QueryInterface().
  // 
  virtual HRESULT InternalQueryInterface(REFIID riid, void **ppvObjOut);


public:
  //
  // This class as concrete. All AAF objects can be constructed from
  // a CLSID. This will allow subclassing all "base-classes" by
  // aggreggation.
  // 
  AAF_DECLARE_CONCRETE();
  //
  //********

  // Declare the module test method. The implementation of the will be be
  // in /test/C.this-moduleTest.cpp.
  static HRESULT test();

  //
  // Return private implementation pointer for delegation.
  // NOTE: This is NOT the pointer to the COM object's implementation
  // object!
  //
  STDMETHOD(GetImplRep)(/*[retval, string, out]*/ unsigned char **);

protected:

  Impl.this-module * GetRepObject ();

  void InitRep (Impl.this-module * pObj);

private:

  Impl.this-module * _rep;

};

#endif // ! __C.this-module_h__
#endm


#ccccccccccccccccccccccccccc
#c
#c Specifies an overridden method
#c
#c Argument: method declaration
#c
#startm AD_OVERRIDE 01
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a constructor which takes one argument.
#c Constructor name is assumed to be .this-module.
#c
#c Macro arguments 01+:
#c 
#c meth arg #   arg modfrs   obj style   type    name    arg cmnt
#c ----------   ----------   ---------   ----    ----    --------
#c metharg 1    01           02          03      04      05
#c
#c Macro Arg 06: method description
#c
#startm AD_XCONSTRUCTOR1 06
    C.this-module (.%02-adornment%03 .%02-indirection %04);\
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a constructor which takes two arguments.
#c Constructor name is assumed to be .this-module.
#c
#c Macro arguments 01+:
#c 
#c meth arg #   arg modfrs   obj style   type    name    arg cmnt
#c ----------   ----------   ---------   ----    ----    --------
#c metharg 1    01           02          03      04      05
#c metharg 2    06           07          08      09      10
#c
#c Macro Arg 11: method description
#c
#startm AD_XCONSTRUCTOR2 11
    C.this-module (.%02-adornment%03 .%02-indirection %04,
		.%07-adornment%08 .%07-indirection %09);\
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a constructor which takes three arguments.
#c Constructor name is assumed to be .this-module.
#c
#c Macro arguments 01+:
#c 
#c meth arg #   arg modfrs   obj style   type    name    arg cmnt
#c ----------   ----------   ---------   ----    ----    --------
#c metharg 1    01           02          03      04      05
#c metharg 2    06           07          08      09      10
#c metharg 3    11           12          13      14      15
#c
#c Macro Arg 16: method description
#c
#startm AD_XCONSTRUCTOR3 16
    C.this-module (.%07-adornment%03 .%02-indirection %04,
		.%07-adornment%08 .%07-indirection %09,
		.%12-adornment%13 .%12-indirection %14);\
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a constructor which takes four arguments.
#c Constructor name is assumed to be .this-module.
#c
#c Macro arguments 01+:
#c 
#c meth arg #   arg modfrs   obj style   type    name    arg cmnt
#c ----------   ----------   ---------   ----    ----    --------
#c metharg 1    01           02          03      04      05
#c metharg 2    06           07          08      09      10
#c metharg 3    11           12          13      14      15
#c metharg 4    16           17          18      19      20
#c
#c Macro Arg 21: method description
#c
#startm AD_XCONSTRUCTOR4 21
    C.this-module (.%02-adornment%03 .%02-indirection %04,
		.%07-adornment%08 .%07-indirection %09,
		.%12-adornment%13 .%12-indirection %14,
		.%17-adornment%18 .%17-indirection %19);\
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a method which takes one argument, which is
#c a pointer to an AAF object which is to be returned to the caller.
#c This is different from the normal METHOD macro because the
#c _rep will probably have the object in a different form.
#c
#c Argument1: method name
#c Argument2: argument modifiers (e.g. [in])
#c Argument3: argument type
#c Argument4: argument name
#c Argument5: argument comment
#c Argument6: method description
#c
#c NOTE!!! This macro takes as type, the object itself, not the
#c pointer to it.  The indirection will be added by the macro
#c expansion.
#c
#startm AD_GETOBJ_METHOD1 06
  virtual AAFRESULT STDMETHODCALLTYPE
    %01 (I%03 ** %04);\
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a method which takes one argument, which is
#c a pointer to an AAF object which is to be passed in from the caller.
#c This is different from the normal METHOD macro because the
#c _rep will probably have the object in a different form.
#c
#c NOTE!!! This macro takes as type, the object itself, not the
#c pointer to it.  The indirection will be added by the macro
#c expansion.
#c
#c Argument1: method name
#c Argument2: argument modifiers (e.g. [in])
#c Argument3: argument type
#c Argument4: argument name
#c Argument5: argument comment
#c Argument6: method description
#c
#startm AD_SETOBJ_METHOD1 06
  virtual AAFRESULT STDMETHODCALLTYPE
    %01 (I%03 * %04);\
#endm

#ccccccccccccccccccccccccccc
#c
#c Argument1: text to be quoted.
#c 
#c Just pass through the input. 
#c
#c This should not actually be used since the midl compiler will normally generate
#c the associated com cpp interface file. Included here for completeness and 
#c testing puposes only.
#c
#c TomR:added 980714
#c
#startm AD_CPP_QUOTE 01
%01 \
#endm


#ccccccccccccccccccccccccccc
#c
#c Argument1: base name to be converted to output type.
#c NOTE: The \n is escaped so that the macro can be used
#c in a statement without emitting a new line.
#c
#c This should not actually be used since the midl compiler will normally generate
#c the associated com cpp interface file. Included here for completeness and 
#c testing puposes only.
#c
#c TomR:added 980714
#c
#startm AD_AAFTYPES 01
I%01 \
#endm


#ccccccccccccccccccccccccccc
#c
#c Argument1: base name to be converted to output type.
#c
#c This should not actually be used since the midl compiler will normally generate
#c the associated com cpp interface file. Included here for completeness and 
#c testing puposes only.
#c
#c TomR:added 980714
#c
#startm AD_DECLARE_FORWARD_AAFTYPES 01
#endm

#ccccccccccccccccccccccccccc
#c
#c Argument1: base name to be converted to output type.
#c
#c This is ignored since forward declarations will be created
#c by the midl generated header.
#startm AD_FORWARD_DECLARATION 01
#endm


#ccccccccccccccccccccccccccc
#c
#c Defining the interface UUID.
#c NOTE: Should be placed immediately before AD_CLASS_BEGIN
#c This symbol is generated by the midl compiler.
#c
#startm AD_DEFAULT_UUID 11
#endm


#ccccccccccccccccccccccccccc
#c
#c Defining the Class "Factory" UUID.
#c NOTE: should be placed before AD_DEFAULT_UUID or after
#c AD_CLASS_END
#c This symbol is generated by the midl compiler.
#c
#startm AD_CLASS_UUID 11
#endm


#ccccccccccccccccccccccccccc
#c
#c The following macros assist in passing arguments to methods of the
#c contained implementation class:
#c
#c The objIn macros are for use with pointers to objects that are
#c passed into the method.  The Type argument is the base type, with
#c no indirection specified.  For example, if you're passing in
#c AObject*, AObject should be specified for the Type argument.#c
#c
#c The objOut macros are for use with pointers to pointers to objects
#c that are passed out of the method.  The Type argument is the base
#c type, with no indirection specified.  For example, if you're
#c passing in AObject**, AObject should be specified for the Type
#c argument.
#c
#c The objPass macros are for use with any kind of data which is
#c passed exactly into or out of the method.
#c


#startm .objIn-adornment 00
I\
#endm


#startm .objPass-adornment 00
#endm


#startm .objOut-adornment 00
I\
#endm
