#c /******************************************\
#c *                                          *
#c * Advanced Authoring Format                *
#c *                                          *
#c * Copyright (c) 1998 Avid Technology, Inc. *
#c * Copyright (c) 1998 Microsoft Corporation *
#c *                                          *
#c \******************************************/



#ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
#c
#c AutoDodo macro file for use in generating fractional IDL files;
#c that is, IDL fragments that will eventually be combined into one
#c IDL file.
#c
#ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc


#import macros/base.mac


#ccccccccccccccccccccccccccc
#c
#c Pass through argument if for idl otherwise omit it.
#c 
#c This macro is generally used to specify IDL options that would
#c make since to emit to c++.
#c To allow proper marshalling code generation of a struct: |
#c typedef struct
#c {
#c     aafInt32 length;
#c     AD_IDL([length_is(length)]) aafWchar *str;
#c } aafString_t;
#c
#startm AD_IDL 01
%01\
#endm


#ccccccccccccccccccccccccccc
#c
#c Includes another file.
#c
#c Argument: Base filename
#c
#startm AD_INCLUDE 01
#endm


#ccccccccccccccccccccccccccc
#c
#c Goes at the head of the file.
#c
#c Arguments: none
#c
#startm AD_HEAD 00
// ************************
//
// Interface I.this-module
//
// ************************\
#endm

#ccccccccccccccccccccccccccc
#c
#c Goes at the head of the file.
#c
#c Arguments: none
#c
#startm AD_TYPES_HEAD 00
cpp_quote("//=--------------------------------------------------------------------------=")
cpp_quote("// .this-module.h")
cpp_quote("//=--------------------------------------------------------------------------=")
cpp_quote("// (C) Copyright 1998 Avid Technology.")
cpp_quote("// (C) Copyright 1998 Microsoft Corporation.")
cpp_quote("//")
cpp_quote("// THIS CODE AND INFORMATION IS PROVIDED 'AS IS' WITHOUT WARRANTY OF")
cpp_quote("// ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO")
cpp_quote("// THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A")
cpp_quote("// PARTICULAR PURPOSE.")
cpp_quote("//=--------------------------------------------------------------------------=")
cpp_quote("// .this-module Interface.")
cpp_quote("//=--------------------------------------------------------------------------=")
cpp_quote("//")

#ifndef DO_NO_IMPORTS
import "wtypes.idl";
#endif\
#endm



#ccccccccccccccccccccccccccc
#c
#c Starts a class definition
#c
#c Arguments: none
#c
#startm AD_CLASS_BEGIN 00
interface I.this-module : IUnknown
{\
#endm


#ccccccccccccccccccccccccccc
#c
#c Ends a class definition for classes which support more than the
#c primary COM interface.
#c
#c Arguments: additional interface name
#c
#startm AD_COM_EXT_CLASS_BEGIN 01
AD_CLASS_BEGIN\
#endm


#ccccccccccccccccccccccccccc
#c
#c Starts a class definition with no parent class
#c
#c Arguments: none
#c
#startm AD_ROOT_CLASS_BEGIN 00
AD_CLASS_BEGIN\
#endm


#ccccccccccccccccccccccccccc
#c
#c Types definitions should only be used by idl and c++ & impl headers
#c 
#c
#c GUID
#c Argument01: hex long  0-3[leading 0's w/o leading 0x]
#c Argument02: hex short 4-5[leading 0's w/o leading 0x]
#c Argument03: hex short 6-7[leading 0's w/o leading 0x]
#c Argument04: hex byte   8 [leading 0's w/o leading 0x]
#c Argument05: hex byte   9 [leading 0's w/o leading 0x]
#c Argument06: hex byte  10 [leading 0's w/o leading 0x]
#c Argument07: hex byte  11 [leading 0's w/o leading 0x]
#c Argument08: hex byte  12 [leading 0's w/o leading 0x]
#c Argument09: hex byte  13 [leading 0's w/o leading 0x]
#c Argument10: hex byte  14 [leading 0's w/o leading 0x]
#c Argument11: hex byte  15 [leading 0's w/o leading 0x]
#c
#c Example:
#c AD_TYPES_BEGIN(b1a21372, 1a7d, 11d2, bf, 78, 00, 10, 4b, c9, 15, 6d)
#c
#startm AD_TYPES_BEGIN 11
[
    uuid(%01-%02-%03-%04%05-%06%07%08%09%10%11),
    pointer_default(unique)
]

interface I.this-module
{\
#endm


#ccccccccccccccccccccccccccc
#c
#c Ends a types definition
#c
#c Types definitions should only be used by idl and c++ & impl headers. This should
#c be the last line of a "types" dodo file.
#c
#c Arguments: none
#c
#startm AD_TYPES_END 00
}\
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a method which takes no arguments.
#c
#c Argument1: method name
#c Argument2: method description
#c
#startm AD_METHOD0 02
  //***********************************************************
  //
  // %01()
  //
  // %02
  // 
  HRESULT %01 ();\
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a method which takes one argument.
#c
#c Macro Arg 01: method name
#c
#c Macro arguments 02+:
#c 
#c meth arg #   arg modfrs   obj style   type    name    arg cmnt
#c ----------   ----------   ---------   ----    ----    --------
#c metharg 1    02           03          04      05      06
#c
#c Macro Arg 07: method description
#c
#startm AD_XMETHOD1 07
  //***********************************************************
  //
  // %01()
  //
  // %07
  // 
  HRESULT %01 (
    // %06
    %02 .%03-adornment%04 .%03-indirection %05);\
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a method which takes two arguments.
#c
#c Macro Arg 01: method name
#c
#c Macro arguments 02+:
#c 
#c meth arg #   arg modfrs   obj style   type    name    arg cmnt
#c ----------   ----------   ---------   ----    ----    --------
#c metharg 1    02           03          04      05      06
#c metharg 2    07           08          09      10      11
#c
#c Macro Arg 12: method description
#c
#startm AD_XMETHOD2 12
  //***********************************************************
  //
  // %01()
  //
  // %12
  // 
  HRESULT %01 (
    // %06
    %02 .%03-adornment%04 .%03-indirection %05,

    // %11
    %07 .%08-adornment%09 .%08-indirection %10);\
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a method which takes three arguments.
#c
#c Macro Arg 01: method name
#c
#c Macro arguments 02+:
#c 
#c meth arg #   arg modfrs   obj style   type    name    arg cmnt
#c ----------   ----------   ---------   ----    ----    --------
#c metharg 1    02           03          04      05      06
#c metharg 2    07           08          09      10      11
#c metharg 3    12           13          14      15      16
#c
#c Macro Arg 17: method description
#c
#startm AD_XMETHOD3 17
  //***********************************************************
  //
  // %01()
  //
  // %17
  // 
  HRESULT %01 (
    // %06
    %02 .%03-adornment%04 .%03-indirection %05,

    // %11
    %07 .%08-adornment%09 .%08-indirection %10,

    // %16
    %12 .%13-adornment%14 .%13-indirection %15);\
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a method which takes four arguments.
#c
#c Macro Arg 01: method name
#c
#c Macro arguments 02+:
#c 
#c meth arg #   arg modfrs   obj style   type    name    arg cmnt
#c ----------   ----------   ---------   ----    ----    --------
#c metharg 1    02           03          04      05      06
#c metharg 2    07           08          09      10      11
#c metharg 3    12           13          14      15      16
#c metharg 4    17           18          19      20      21
#c
#c Macro Arg 22: method description
#c
#startm AD_XMETHOD4 22
  //***********************************************************
  //
  // %01()
  //
  // %22
  // 
  HRESULT %01 (
    // %06
    %02 .%03-adornment%04 .%03-indirection %05,

    // %11
    %07 .%08-adornment%09 .%08-indirection %10,

    // %16
    %12 .%13-adornment%14 .%13-indirection %15,

    // %21
    %17 .%18-adornment%19 .%18-indirection %20);\
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a method which takes five arguments.
#c
#c Macro Arg 01: method name
#c
#c Macro arguments 02+:
#c 
#c meth arg #   arg modfrs   obj style   type    name    arg cmnt
#c ----------   ----------   ---------   ----    ----    --------
#c metharg 1    02           03          04      05      06
#c metharg 2    07           08          09      10      11
#c metharg 3    12           13          14      15      16
#c metharg 4    17           18          19      20      21
#c metharg 5    22           23          24      25      26
#c
#c Macro Arg 27: method description
#c
#startm AD_XMETHOD5 27
  //***********************************************************
  //
  // %01()
  //
  // %27
  // 
  HRESULT %01 (
    // %06
    %02 .%03-adornment%04 .%03-indirection %05,

    // %11
    %07 .%08-adornment%09 .%08-indirection %10,

    // %16
    %12 .%13-adornment%14 .%13-indirection %15,

    // %21
    %17 .%18-adornment%19 .%18-indirection %20,

    // %26
    %22 .%23-adornment%24 .%23-indirection %25);\
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a method which takes six arguments.
#c
#c Macro Arg 01: method name
#c
#c Macro arguments 02+:
#c 
#c meth arg #   arg modfrs   obj style   type    name    arg cmnt
#c ----------   ----------   ---------   ----    ----    --------
#c metharg 1    02           03          04      05      06
#c metharg 2    07           08          09      10      11
#c metharg 3    12           13          14      15      16
#c metharg 4    17           18          19      20      21
#c metharg 5    22           23          24      25      26
#c metharg 6    27           28          29      30      31
#c
#c Macro Arg 32: method description
#c
#startm AD_XMETHOD6 32
  //***********************************************************
  //
  // %01()
  //
  // %32
  // 
  HRESULT %01 (
    // %06
    %02 .%03-adornment%04 .%03-indirection %05,

    // %11
    %07 .%08-adornment%09 .%08-indirection %10,

    // %16
    %12 .%13-adornment%14 .%13-indirection %15,

    // %21
    %17 .%18-adornment%19 .%18-indirection %20,

    // %26
    %22 .%23-adornment%24 .%23-indirection %25,

    // %31
    %27 .%28-adornment%29 .%28-indirection %30);\
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a method which takes seven arguments.
#c
#c Macro Arg 01: method name
#c
#c Macro arguments 02+:
#c 
#c meth arg #   arg modfrs   obj style   type    name    arg cmnt
#c ----------   ----------   ---------   ----    ----    --------
#c metharg 1    02           03          04      05      06
#c metharg 2    07           08          09      10      11
#c metharg 3    12           13          14      15      16
#c metharg 4    17           18          19      20      21
#c metharg 5    22           23          24      25      26
#c metharg 6    27           28          29      30      31
#c metharg 7    32           33          34      35      36
#c
#c Macro Arg 37: method description
#c
#startm AD_XMETHOD7 37
  //***********************************************************
  //
  // %01()
  //
  // %37
  // 
  HRESULT %01 (
    // %06
    %02 .%03-adornment%04 .%03-indirection %05,

    // %11
    %07 .%08-adornment%09 .%08-indirection %10,

    // %16
    %12 .%13-adornment%14 .%13-indirection %15,

    // %21
    %17 .%18-adornment%19 .%18-indirection %20,

    // %26
    %22 .%23-adornment%24 .%23-indirection %25,

    // %31
    %27 .%28-adornment%29 .%28-indirection %30,

    // %36
    %32 .%33-adornment%34 .%33-indirection %35);\
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a method which takes eight arguments.
#c
#c Macro Arg 01: method name
#c
#c Macro arguments 02+:
#c 
#c meth arg #   arg modfrs   obj style   type    name    arg cmnt
#c ----------   ----------   ---------   ----    ----    --------
#c metharg 1    02           03          04      05      06
#c metharg 2    07           08          09      10      11
#c metharg 3    12           13          14      15      16
#c metharg 4    17           18          19      20      21
#c metharg 5    22           23          24      25      26
#c metharg 6    27           28          29      30      31
#c metharg 7    32           33          34      35      36
#c metharg 8    37           38          39      40      41
#c
#c Macro Arg 42: method description
#c
#startm AD_XMETHOD8 42
  //***********************************************************
  //
  // %01()
  //
  // %42
  // 
  HRESULT %01 (
    // %06
    %02 .%03-adornment%04 .%03-indirection %05,

    // %11
    %07 .%08-adornment%09 .%08-indirection %10,

    // %16
    %12 .%13-adornment%14 .%13-indirection %15,

    // %21
    %17 .%18-adornment%19 .%18-indirection %20,

    // %26
    %22 .%23-adornment%24 .%23-indirection %25,

    // %31
    %27 .%28-adornment%29 .%28-indirection %30,

    // %36
    %32 .%33-adornment%34 .%33-indirection %35,

    // %41
    %37 .%38-adornment%39 .%38-indirection %40);\
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a method which takes nine arguments.
#c
#c Macro Arg 01: method name
#c
#c Macro arguments 02+:
#c 
#c meth arg #   arg modfrs   obj style   type    name    arg cmnt
#c ----------   ----------   ---------   ----    ----    --------
#c metharg 1    02           03          04      05      06
#c metharg 2    07           08          09      10      11
#c metharg 3    12           13          14      15      16
#c metharg 4    17           18          19      20      21
#c metharg 5    22           23          24      25      26
#c metharg 6    27           28          29      30      31
#c metharg 7    32           33          34      35      36
#c metharg 8    37           38          39      40      41
#c metharg 9    42           43          44      45      46
#c
#c Macro Arg 47: method description
#c
#startm AD_XMETHOD9 47
  //***********************************************************
  //
  // %01()
  //
  // %47
  // 
  HRESULT %01 (
    // %06
    %02 .%03-adornment%04 .%03-indirection %05,

    // %11
    %07 .%08-adornment%09 .%08-indirection %10,

    // %16
    %12 .%13-adornment%14 .%13-indirection %15,

    // %21
    %17 .%18-adornment%19 .%18-indirection %20,

    // %26
    %22 .%23-adornment%24 .%23-indirection %25,

    // %31
    %27 .%28-adornment%29 .%28-indirection %30,

    // %36
    %32 .%33-adornment%34 .%33-indirection %35,

    // %41
    %37 .%38-adornment%39 .%38-indirection %40,

    // %46
    %42 .%43-adornment%44 .%43-indirection %45);\
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a method which takes ten arguments.
#c
#c Macro Arg 01: method name
#c
#c Macro arguments 02+:
#c 
#c meth arg #   arg modfrs   obj style   type    name    arg cmnt
#c ----------   ----------   ---------   ----    ----    --------
#c metharg 1    02           03          04      05      06
#c metharg 2    07           08          09      10      11
#c metharg 3    12           13          14      15      16
#c metharg 4    17           18          19      20      21
#c metharg 5    22           23          24      25      26
#c metharg 6    27           28          29      30      31
#c metharg 7    32           33          34      35      36
#c metharg 8    37           38          39      40      41
#c metharg 9    42           43          44      45      46
#c metharg 10   47           48          49      50      51
#c
#c Macro Arg 52: method description
#c
#startm AD_XMETHOD_10 52
  //***********************************************************
  //
  // %01()
  //
  // %52
  // 
  HRESULT %01 (
    // %06
    %02 .%03-adornment%04 .%03-indirection %05,

    // %11
    %07 .%08-adornment%09 .%08-indirection %10,

    // %16
    %12 .%13-adornment%14 .%13-indirection %15,

    // %21
    %17 .%18-adornment%19 .%18-indirection %20,

    // %26
    %22 .%23-adornment%24 .%23-indirection %25,

    // %31
    %27 .%28-adornment%29 .%28-indirection %30,

    // %36
    %32 .%33-adornment%34 .%33-indirection %35,

    // %41
    %37 .%38-adornment%39 .%38-indirection %40,

    // %46
    %42 .%43-adornment%44 .%43-indirection %45,

    // %51
    %47 .%48-adornment%49 .%48-indirection %50);\
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a method which takes eleven arguments.
#c
#c Macro Arg 01: method name
#c
#c Macro arguments 02+:
#c 
#c meth arg #   arg modfrs   obj style   type    name    arg cmnt
#c ----------   ----------   ---------   ----    ----    --------
#c metharg 1    02           03          04      05      06
#c metharg 2    07           08          09      10      11
#c metharg 3    12           13          14      15      16
#c metharg 4    17           18          19      20      21
#c metharg 5    22           23          24      25      26
#c metharg 6    27           28          29      30      31
#c metharg 7    32           33          34      35      36
#c metharg 8    37           38          39      40      41
#c metharg 9    42           43          44      45      46
#c metharg 10   47           48          49      50      51
#c metharg 11   52           53          54      55      56
#c
#c Macro Arg 57: method description
#c
#startm AD_XMETHOD_11 57
  //***********************************************************
  //
  // %01()
  //
  // %57
  // 
  HRESULT %01 (
    // %06
    %02 .%03-adornment%04 .%03-indirection %05,

    // %11
    %07 .%08-adornment%09 .%08-indirection %10,

    // %16
    %12 .%13-adornment%14 .%13-indirection %15,

    // %21
    %17 .%18-adornment%19 .%18-indirection %20,

    // %26
    %22 .%23-adornment%24 .%23-indirection %25,

    // %31
    %27 .%28-adornment%29 .%28-indirection %30,

    // %36
    %32 .%33-adornment%34 .%33-indirection %35,

    // %41
    %37 .%38-adornment%39 .%38-indirection %40,

    // %46
    %42 .%43-adornment%44 .%43-indirection %45,

    // %51
    %47 .%48-adornment%49 .%48-indirection %50,

    // %56
    %52 .%53-adornment%54 .%53-indirection %55);\
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a method which takes three arguments.
#c Allows an additional macro argument per method argument to let
#c macro caller pass more info.  For example:
#c
#c For type           Arg is
#c     ----           ------
#c     objInArray     array size
#c     objOutArray    array size
#c     objInCustom    custom input "marshal" code
#c     objOutCustom   custom output "marshal" code
#c     all else       ignored
#c
#c Macro Arg 01: method name
#c
#c Macro arguments 02+:
#c 
#c meth arg #   arg modfrs   obj style   type    name    arg cmnt aux
#c ----------   ----------   ---------   ----    ----    -------- --
#c metharg 1    02           03          04      05      06       07
#c metharg 2    08           09          10      11      12       13
#c metharg 3    14           15          16      17      18       19
#c
#c Macro Arg 20: method description
#c
#startm AD_X2METHOD3 20
  //***********************************************************
  //
  // %01()
  //
  // %20
  // 
  HRESULT %01 (
    // %06
    %02 .%03-adornment%04 .%03-indirection %05,

    // %12
    %08 .%09-adornment%10 .%09-indirection %11,

    // %18
    %14 .%15-adornment%16 .%15-indirection %17);\
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a method which takes four arguments.
#c Allows an additional macro argument per method argument to let
#c macro caller pass more info.  For example:
#c
#c For type           Arg is
#c     ----           ------
#c     objInArray     array size
#c     objOutArray    array size
#c     objInCustom    custom input "marshal" code
#c     objOutCustom   custom output "marshal" code
#c     all else       ignored
#c
#c Macro Arg 01: method name
#c
#c Macro arguments 02+:
#c 
#c meth arg #   arg modfrs   obj style   type    name    arg cmnt aux
#c ----------   ----------   ---------   ----    ----    -------- --
#c metharg 1    02           03          04      05      06       07
#c metharg 2    08           09          10      11      12       13
#c metharg 3    14           15          16      17      18       19
#c metharg 4    20           21          22      23      24       25
#c
#c Macro Arg 26: method description
#c
#startm AD_X2METHOD4 26
  //***********************************************************
  //
  // %01()
  //
  // %26
  // 
  HRESULT %01 (
    // %06
    %02 .%03-adornment%04 .%03-indirection %05,

    // %12
    %08 .%09-adornment%10 .%09-indirection %11,

    // %18
    %14 .%15-adornment%16 .%15-indirection %17,

    // %24
    %20 .%21-adornment%22 .%21-indirection %23);\
#endm


#ccccccccccccccccccccccccccc
#c
#c Forward declaration of another interface.
#c
#c Argument: Base name
#c
#startm AD_FORWARD_DECLARATION 01
#endm


#ccccccccccccccccccccccccccc
#c
#c Defining the interface UUID.
#c NOTE: Should be placed immediately before AD_CLASS_BEGIN
#c
#c GUID
#c Argument01: hex long  0-3[leading 0's w/o leading 0x]
#c Argument02: hex short 4-5[leading 0's w/o leading 0x]
#c Argument03: hex short 6-7[leading 0's w/o leading 0x]
#c Argument04: hex byte   8 [leading 0's w/o leading 0x]
#c Argument05: hex byte   9 [leading 0's w/o leading 0x]
#c Argument06: hex byte  10 [leading 0's w/o leading 0x]
#c Argument07: hex byte  11 [leading 0's w/o leading 0x]
#c Argument08: hex byte  12 [leading 0's w/o leading 0x]
#c Argument09: hex byte  13 [leading 0's w/o leading 0x]
#c Argument10: hex byte  14 [leading 0's w/o leading 0x]
#c Argument11: hex byte  15 [leading 0's w/o leading 0x]
#c
#c Example:
#c AD_DEFAULT_UUID(b1a21372, 1a7d, 11d2, bf, 78, 00, 10, 4b, c9, 15, 6d)
#c
#c
#startm AD_DEFAULT_UUID 11
[
    object,
    uuid(%01-%02-%03-%04%05-%06%07%08%09%10%11),
    helpstring("I.this-module Interface"),
    pointer_default(unique)
]\
#endm


#ccccccccccccccccccccccccccc
#c
#c Defining the Class "Factory" UUID.
#c NOTE: should be placed before AD_DEFAULT_UUID or after
#c AD_CLASS_UUID
#c
#c GUID
#c Argument01: hex long  0-3[leading 0's w/o leading 0x]
#c Argument02: hex short 4-5[leading 0's w/o leading 0x]
#c Argument03: hex short 6-7[leading 0's w/o leading 0x]
#c Argument04: hex byte   8 [leading 0's w/o leading 0x]
#c Argument05: hex byte   9 [leading 0's w/o leading 0x]
#c Argument06: hex byte  10 [leading 0's w/o leading 0x]
#c Argument07: hex byte  11 [leading 0's w/o leading 0x]
#c Argument08: hex byte  12 [leading 0's w/o leading 0x]
#c Argument09: hex byte  13 [leading 0's w/o leading 0x]
#c Argument10: hex byte  14 [leading 0's w/o leading 0x]
#c Argument11: hex byte  15 [leading 0's w/o leading 0x]
#c
#c Example:
#c AD_CLASS_UUID(b1a21373, 1a7d, 11d2, bf, 78, 00, 10, 4b, c9, 15, 6d)
#c
#c TomR:980713: Added
#c TomR:990303: Removed
#c cpp_quote("EXTERN_C const CLSID CLSID_.this-module;")
#c
#startm AD_CLASS_UUID 11
#endm


#ccccccccccccccccccccccccccc
#c
#c Ends a class definition
#c
#c Arguments: none
#c
#startm AD_CLASS_END 00
}\
#endm


#ccccccccccccccccccccccccccc
#c
#c Ends a class definition for classes which support more than the
#c primary COM interface.
#c
#c Arguments: additional interface name
#c
#startm AD_COM_EXT_CLASS_END 01
AD_CLASS_END\
#endm


#ccccccccccccccccccccccccccc
#c
#c Ends a class definition
#c
#c Arguments: none
#c
#startm AD_ROOT_CLASS_END 00
  //
  // Return private implementation pointer for delegation.
  // NOTE: This is NOT the pointer to the COM object's implementation
  // object!
  //
  [local] HRESULT GetImplRep([out, retval] void **);
}\
#endm


#ccccccccccccccccccccccccccc
#c
#c Specifies an overridden method
#c
#c Argument: method declaration
#c
#startm AD_OVERRIDE 01
#endm


#ccccccccccccccccccccccccccc
#c
#c Specifies a method in a separate COM interface.
#c
#c Argument: method declaration
#c
#startm AD_COM_METH 01
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a constructor which takes one argument.
#c Constructor name is assumed to be .this-module.
#c
#c Macro arguments 01+:
#c 
#c meth arg #   arg modfrs   obj style   type    name    arg cmnt
#c ----------   ----------   ---------   ----    ----    --------
#c metharg 1    01           02          03      04      05
#c
#c Macro Arg 06: method description
#c
#startm AD_XCONSTRUCTOR1 06
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a constructor which takes two arguments.
#c Constructor name is assumed to be .this-module.
#c
#c Macro arguments 01+:
#c 
#c meth arg #   arg modfrs   obj style   type    name    arg cmnt
#c ----------   ----------   ---------   ----    ----    --------
#c metharg 1    01           02          03      04      05
#c metharg 2    06           07          08      09      10
#c
#c Macro Arg 11: method description
#c
#startm AD_XCONSTRUCTOR2 11
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a constructor which takes three arguments.
#c Constructor name is assumed to be .this-module.
#c
#c Macro arguments 01+:
#c 
#c meth arg #   arg modfrs   obj style   type    name    arg cmnt
#c ----------   ----------   ---------   ----    ----    --------
#c metharg 1    01           02          03      04      05
#c metharg 2    06           07          08      09      10
#c metharg 3    11           12          13      14      15
#c
#c Macro Arg 16: method description
#c
#startm AD_XCONSTRUCTOR3 16
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a constructor which takes four arguments.
#c Constructor name is assumed to be .this-module.
#c
#c Macro arguments 01+:
#c 
#c meth arg #   arg modfrs   obj style   type    name    arg cmnt
#c ----------   ----------   ---------   ----    ----    --------
#c metharg 1    01           02          03      04      05
#c metharg 2    06           07          08      09      10
#c metharg 3    11           12          13      14      15
#c metharg 4    16           17          18      19      20
#c
#c Macro Arg 21: method description
#c
#startm AD_XCONSTRUCTOR4 21
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a method which takes one argument, which is
#c a pointer to an AAF object which is to be returned to the caller.
#c This is different from the normal METHOD macro because the
#c _rep will probably have the object in a different form.
#c
#c Argument1: method name
#c Argument2: argument modifiers (e.g. [in])
#c Argument3: argument type
#c Argument4: argument name
#c Argument5: argument comment
#c Argument6: method description
#c
#startm AD_GETOBJ_METHOD1 06
  // %06
  HRESULT %01 (
    %02 %03 ** I%04);\
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a method which takes one argument, which is
#c a pointer to an AAF object which is to be passed in from the caller.
#c This is different from the normal METHOD macro because the
#c _rep will probably have the object in a different form.
#c
#c Argument1: method name
#c Argument2: argument modifiers (e.g. [in])
#c Argument3: argument type
#c Argument4: argument name
#c Argument5: argument comment
#c Argument6: method description
#c
#startm AD_SETOBJ_METHOD1 06
  // %06
  HRESULT %01 (
    %02 %03 * I%04);\
#endm


#ccccccccccccccccccccccccccc
#c
#c Argument1: text to be quoted.
#c 
#c Just pass through the input quoted to cpp_quote and then
#c let the midl compiler pass the quoted text to its ???.h 
#c output.
#c
#c TomR:added 980714
#c
#startm AD_CPP_QUOTE 01
cpp_quote("%01") \
#endm


#ccccccccccccccccccccccccccc
#c
#c Argument1: base name to be converted to output type.
#c NOTE: The \n is escaped so that the macro can be used
#c in a statement without emitting a new line.
#c
#c TomR:added 980714
#c
#startm AD_AAFTYPES 01
I%01 \
#endm


#ccccccccccccccccccccccccccc
#c
#c Argument1: base name to be converted to output type.
#c
#c TomR:added 980714
#c
#startm AD_DECLARE_FORWARD_AAFTYPES 01
interface I%01;\
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a static method used to bootstrap an AAF
#c session by creating the first session object.
#c
#startm AD_BEGIN_SESSION 00
#endm

#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a static method used for a container to create
#c its contained objects in the cpp API.
#c
#startm AD_STATIC_CREATE 00
#endm


#ccccccccccccccccccccccccccc
#c
#c The following macros assist in passing arguments to methods of the
#c contained implementation class:
#c
#c The objIn macros are for use with pointers to objects that are
#c passed into the method.  The Type argument is the base type, with
#c no indirection specified.  For example, if you're passing in
#c AObject*, AObject should be specified for the Type argument.#c
#c
#c The objOut macros are for use with pointers to pointers to objects
#c that are passed out of the method.  The Type argument is the base
#c type, with no indirection specified.  For example, if you're
#c passing in AObject**, AObject should be specified for the Type
#c argument.
#c
#c The objPass macros are for use with any kind of data which is
#c passed exactly into or out of the method.
#c


#startm .objIn-adornment 00
I\
#endm


#startm .objInArray-adornment 00
I\
#endm


#startm .objInArrayCustom-adornment 00
#endm


#startm .objPass-adornment 00
#endm


#startm .objOut-adornment 00
I\
#endm


#startm .objOutArray-adornment 00
I\
#endm


#startm .objOutArrayCustom-adornment 00
#endm


#ccccccccccccccccccccccccccc
#c
#c Hack to quote the .this-module macro and keep it out of export
#c files.  Do not define this macro in exp.mac!!!
#c
#startm AD_EXPORT_THIS_MODULE 00
.this-module\
#endm


#ccccccccccccccccccccccccccc
#c
#c Starts a class definition
#c
#c Argument1: Abstract or Concrete
#c Argument2: Transient or StoredObject
#c            special cases:CommonBase and StoredObjectBase
#c
#c Note: Concrete-StoredObject means Persistent. In other words
#c Concrete-StoredObject objects (and derived objects) are the 
#c only types of objects that should ever be found in an AAF
#c file.
#c
#c Valid combiniations:          examples
#c -----------------------       ---------------
#c   Abstract-CommonBase         AAFRoot 
#c   Abstract-Transient          ????
#c   Abstract-StoredObjectBase   AAFObject
#c   Abstract-StoredObject       AAFSourceReference, AAFComponent, ...
#c   Concrete-Transient          EnumAAFMobs, EnumAAFMobSlots, ...
#c   Concrete-StoredObject       AAFSegment, AAFSourceClip, ...
#c
#startm AD_XCLASS_BEGIN 02
.begin-%01-%02
#endm


#ccccccccccccccccccccccccccc
#c
#c Ends a class definition
#c
#c Argument1: Abstract or Concrete
#c Argument2: Transient or StoredObject
#c            special cases:CommonBase and StoredObjectBase
#c
#c Note: Concrete-StoredObject means Persistent. In other words
#c Concrete-StoredObject objects (and derived objects) are the 
#c only types of objects that should ever be found in an AAF
#c file.
#c
#c Valid combiniations:          examples
#c -----------------------       ---------------
#c   Abstract-CommonBase         AAFRoot 
#c   Abstract-Transient          ????
#c   Abstract-StoredObjectBase   AAFObject
#c   Abstract-StoredObject       AAFSourceReference, AAFComponent, ...
#c   Concrete-Transient          EnumAAFMobs, EnumAAFMobSlots, ...
#c   Concrete-StoredObject       AAFSegment, AAFSourceClip, ...
#c
#startm AD_XCLASS_END 02
.end-%01-%02
#endm


#ccccccccccccccccccccccccccc
#c
#c The following macros implement all of the allowable
#c combinations of the AD_XCLASS_BEGIN and AD_XCLASS_END
#c


#ccccccccccccccccccccccccccc
#c Abstract-CommonBase
#c Special case for the common base class for all AAF objects,
#c Transient and StoredObject classes.
#c (first version defined backwords compatibility)

#startm .begin-Abstract-CommonBase 00
AD_ROOT_CLASS_BEGIN\
#endm

#startm .end-Abstract-CommonBase 00
AD_ROOT_CLASS_END\
#endm


#ccccccccccccccccccccccccccc
#c Abstract-StoredObjectBase
#c Special case for the base class for all AAF stored objects
#c (first version defined backwords compatibility)

#startm .begin-Abstract-StoredObjectBase 00
AD_CLASS_BEGIN\
#endm

#startm .end-Abstract-StoredObjectBase 00
AD_CLASS_END\
#endm


#ccccccccccccccccccccccccccc
#c Abstract-Transient
#c (first version defined backwords compatibility)

#startm .begin-Abstract-Transient 00
AD_CLASS_BEGIN\
#endm

#startm .end-Abstract-Transient 00
AD_CLASS_END\
#endm


#ccccccccccccccccccccccccccc
#c Abstract-StoredObject
#c (first version defined backwords compatibility)

#startm .begin-Abstract-StoredObject 00
AD_CLASS_BEGIN\
#endm

#startm .end-Abstract-StoredObject 00
AD_CLASS_END\
#endm


#ccccccccccccccccccccccccccc
#c Concrete-Transient
#c (first version defined backwords compatibility)

#startm .begin-Concrete-Transient 00
AD_CLASS_BEGIN\
#endm

#startm .end-Concrete-Transient 00
AD_CLASS_END\
#endm


#ccccccccccccccccccccccccccc
#c Concrete-StoredObject
#c Note: These are the persistent classes.
#c (first version defined backwords compatibility)

#startm .begin-Concrete-StoredObject 00
AD_CLASS_BEGIN\
#endm

#startm .end-Concrete-StoredObject 00
AD_CLASS_END\
#endm



#ccccccccccccccccccccccccccc
#c
#c IDL 
#c Declaration for the dictionary's factory method.
#c
#startm AD_DICTIONARY_FACTORY 02
  //***********************************************************
  //
  // %01()
  //
  // %02 
  // 
  HRESULT %01(
    // Class identifier (AUID) of the stored object. This is the
    // corresponding SMPTE identifier (as a GUID) for all predefined
    // built-in classes.
    [in, ref] aafUID_t * pAUID,

    // Reference to the identifier of the interface
    [in, ref] REFIID riid,

    // Address of output variable that receives the 
    // interface pointer requested in riid
    [out, iid_is(riid)] IUnknown ** ppvObject);
#endm


#ccccccccccccccccccccccccccc
#c
#c Some standard comment macros for use where APIs are commented
#c
#c interface-specific macros
#c

#startm AD_STD_COMMENT_IFC_HEADER 00
// In addition to the specific error results listed for each method,
// all methods in this interface may also return one of the following
// values:
// 
// AAFRESULT_NOMEMORY
//   - insufficient system memory is available to perform the
//     operation.
//\
#endm

#startm AD_STD_COMMENT_IFC_INIT 00
// AAFRESULT_NOT_INITIALIZED
//   - This object has not yet had Initialize() called on it through
//     this object's primary interface.  Note that IAAFObject is a
//     primary interface for an abstract class, so it is not
//     appropriate for the Initialize() method to exist in this
//     interface.  The Initialize() method is available through the
//     concrete object's primary interface.
//\
#endm

#startm AD_STD_COMMENT_IFC_STUB 00
/***********************************************\\
*   Stub only.   Implementation not yet added   *
\\***********************************************/\
#endm


#c
#c method-specific macros
#c


#startm AD_STD_COMMENT_METH_ADDREF 01
// *%01 is AddRef()ed before it is returned.
  //\
#endm

#startm AD_STD_COMMENT_METH_ERR_HEADER 00
// This method will return the following codes.  If more than one of
  // the listed errors is in effect, it will return the first one
  // encountered in the order given below:
  // 
  // AAFRESULT_SUCCESS
  //   - succeeded.  (This is the only code indicating success.)
  //\
#endm

#startm AD_STD_COMMENT_METH_STUB 00
// NOTE! Stub only.   Implementation not yet added.
  //\
#endm

#startm AD_STD_COMMENT_METH_ERR_ALREADY_INIT 00
// AAFRESULT_ALREADY_INITIALIZED
  //   - This object has already had Initialize() called on it.
  //\
#endm

#startm AD_STD_COMMENT_METH_ERR_NO_INIT 00
// AAFRESULT_NOT_INITIALIZED
  //   - This object has not yet had Initialize() called on it.
  //\
#endm

#startm AD_STD_COMMENT_METH_ERR_NULL_PARAM 01
// AAFRESULT_NULL_PARAM
  //   - %01 arg is NULL.
  //\
#endm


#ccccccccccccccccccccccccccc
#c Begining of the module definitions
#c
#startm AD_MODULE_BEGIN 02
#endm


#ccccccccccccccccccccccccccc
#c End of the module definitions
#c
#startm AD_MODULE_END 00
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a function which takes no arguments.
#c
#c Argument1: function name
#c Argument2: function description
#c
#startm AD_FUNCTION0 02
  //***********************************************************
  //
  // %01()
  //
  // %02
  //
 
cpp_quote("STDAPI %01 ();")
cpp_quote("")\
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a function which takes one argument.
#c
#c Macro Arg 01: function name
#c
#c Macro arguments 02+:
#c 
#c meth arg #   arg modfrs   obj style   type    name    arg cmnt
#c ----------   ----------   ---------   ----    ----    --------
#c metharg 1    02           03          04      05      06
#c
#c Macro Arg 07: function description
#c
#startm AD_XFUNCTION1 07
  //***********************************************************
  //
  // %01()
  //
  // %07
  // 
  // STDAPI %01 (
    //  %06
    //  %02 .%03-adornment%04 .%03-indirection %05);

cpp_quote("STDAPI %01 (.%03-adornment%04 .%03-indirection %05);")
cpp_quote("")\
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a function which takes two arguments.
#c
#c Macro Arg 01: function name
#c
#c Macro arguments 02+:
#c 
#c meth arg #   arg modfrs   obj style   type    name    arg cmnt
#c ----------   ----------   ---------   ----    ----    --------
#c metharg 1    02           03          04      05      06
#c metharg 2    07           08          09      10      11
#c
#c Macro Arg 12: function description
#c
#startm AD_XFUNCTION2 12
  //***********************************************************
  //
  // %01()
  //
  // %12
  // 
  // STDAPI %01 (
    //  %06
    //  %02 .%03-adornment%04 .%03-indirection %05,
    //
    //  %11
    //  %07 .%08-adornment%09 .%08-indirection %10);

cpp_quote("STDAPI %01 (")
cpp_quote("          .%03-adornment%04 .%03-indirection %05,")
cpp_quote("          .%08-adornment%09 .%08-indirection %10);")
cpp_quote("")\
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a function which takes three arguments.
#c
#c Macro Arg 01: function name
#c
#c Macro arguments 02+:
#c 
#c meth arg #   arg modfrs   obj style   type    name    arg cmnt
#c ----------   ----------   ---------   ----    ----    --------
#c metharg 1    02           03          04      05      06
#c metharg 2    07           08          09      10      11
#c metharg 3    12           13          14      15      16
#c
#c Macro Arg 17: function description
#c
#startm AD_XFUNCTION3 17
  //***********************************************************
  //
  // %01()
  //
  // %17
  // 
  // STDAPI %01 (
    //  %06
    //  %02 .%03-adornment%04 .%03-indirection %05,
    //
    //  %11
    //  %07 .%08-adornment%09 .%08-indirection %10,
    //
    //  %16
    //  %12 .%13-adornment%14 .%13-indirection %15);

cpp_quote("STDAPI %01 (")
cpp_quote("          .%03-adornment%04 .%03-indirection %05,")
cpp_quote("          .%08-adornment%09 .%08-indirection %10,")
cpp_quote("          .%13-adornment%14 .%13-indirection %15);")
cpp_quote("")\
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a function which takes four arguments.
#c
#c Macro Arg 01: function name
#c
#c Macro arguments 02+:
#c 
#c meth arg #   arg modfrs   obj style   type    name    arg cmnt
#c ----------   ----------   ---------   ----    ----    --------
#c metharg 1    02           03          04      05      06
#c metharg 2    07           08          09      10      11
#c metharg 3    12           13          14      15      16
#c metharg 4    17           18          19      20      21
#c
#c Macro Arg 22: function description
#c
#startm AD_XFUNCTION4 22
  //***********************************************************
  //
  // %01()
  //
  // %22
  // 
  // STDAPI %01 (
    //  %06
    //  %02 .%03-adornment%04 .%03-indirection %05,
    //
    //  %11
    //  %07 .%08-adornment%09 .%08-indirection %10,
    //
    //  %16
    //  %12 .%13-adornment%14 .%13-indirection %15,
    //
    //  %21
    //  %17 .%18-adornment%19 .%18-indirection %20);

cpp_quote("STDAPI %01 (")
cpp_quote("          .%03-adornment%04 .%03-indirection %05,")
cpp_quote("          .%08-adornment%09 .%08-indirection %10,")
cpp_quote("          .%13-adornment%14 .%13-indirection %15,")
cpp_quote("          .%18-adornment%19 .%18-indirection %20);")
cpp_quote("")\
#endm
