#c /******************************************\
#c *                                          *
#c * Advanced Authoring Format                *
#c *                                          *
#c * Copyright (c) 1998 Avid Technology, Inc. *
#c * Copyright (c) 1998 Microsoft Corporation *
#c *                                          *
#c \******************************************/



#ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
#c
#c AutoDodo macro file for use in generating C++ API header files.
#c
#ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc


#ccccccccccccccccccccccccccc
#c
#c Includes another file.
#c
#c Argument: Base filename
#c
#startm AD_INCLUDE 01
#ifndef _%01_h_
#include "%01.h"
#endif
#endm

#ccccccccccccccccccccccccccc
#c
#c Types definitions should only be used by idl and c++ & impl headers
#c 
#c Argument: Pieces of UUID
#c
#c Example:
#c AD_TYPES_BEGIN(b1a21372, 1a7d, 11d2, bf, 78, 00, 10, 4b, c9, 15, 6d)
#c
#startm AD_TYPES_BEGIN 11
#endm


#ccccccccccccccccccccccccccc
#c
#c Ends a types definition
#c
#c Types definitions should only be used by idl and c++ & impl headers
#c
#c Arguments: none
#c
#startm AD_TYPES_END 00
#endif // _Impl.this-module_h_
#endm


#ccccccccccccccccccccccccccc
#c
#c Argument1: base name to be converted to output type.
#c
#startm AD_AAFTYPES 01
Impl%01\
#endm


#ccccccccccccccccccccccccccc
#c
#c Argument1: base name to be converted to output type.
#c
#startm AD_DECLARE_FORWARD_AAFTYPES 01
class Impl%01;
#endm

#ccccccccccccccccccccccccccc
#c
#c Argument1: text to be quoted.
#c 
#c Just pass through the input. 
#c
#startm AD_CPP_QUOTE 01
%01 \
#endm

#ccccccccccccccccccccccccccc
#c
#c Generate a forward declaration of a class.
#c
#c Argument: class name
#c
#startm AD_FORWARD_DECLARATION 01
	class %01;
#endm

#ccccccccccccccccccccccccccc
#c
#c Class UUID.
#c
#c Argument: Pieces of UUID
#c
#startm AD_CLASS_UUID 11
#endm

#ccccccccccccccccccccccccccc
#c
#c Default UUID.
#c
#c Argument: Pieces of UUID
#c
#startm AD_DEFAULT_UUID 11
#endm

#ccccccccccccccccccccccccccc
#c
#c Goes at the head of the file.
#c
#c Arguments: none
#c
#startm AD_HEAD 00
//@doc
//@class    .this-module | Implementation class for .this-module
#ifndef _Impl.this-module_h_
#define _Impl.this-module_h_
#endm


#ccccccccccccccccccccccccccc
#c
#c Starts a class definition
#c
#c Arguments: none
#c
#startm AD_CLASS_BEGIN 00

#ifndef _Impl.parent-module_h_
#include "Impl.parent-module.h"
#endif


class Impl.this-module : public Impl.parent-module
{
  public:
  Impl.this-module ();
  virtual ~Impl.this-module ();
  //
  // Constructor/destructor
  //
  //********
#endm


#ccccccccccccccccccccccccccc
#c
#c Starts a class definition
#c
#c Arguments: none
#c
#startm AD_ROOT_CLASS_BEGIN 00
//
// Forward declaration
//
class I.this-module;
class .this-module;


class Impl.this-module
{
public:
  Impl.this-module ();
  ~Impl.this-module ();
  //
  // Constructor/destructor
  //
  //********
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a method which takes no arguments.
#c
#c Argument1: method name
#c Argument2: method description
#c
#startm AD_METHOD0 02
  //****************
  // %01()
  //
  virtual AAFRESULT STDMETHODCALLTYPE
    %01 ();
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a method which takes one argument.
#c
#c Argument1: method name
#c Argument2: argument modifiers (e.g. [in])
#c Argument3: argument type
#c Argument4: argument name
#c Argument5: argument comment
#c Argument6: method description
#c
#startm AD_METHOD1 06
  //****************
  // %01()
  //
  virtual AAFRESULT STDMETHODCALLTYPE
    %01
        (%03 %04);  //@parm %02 %05
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a method which takes two arguments.
#c
#c Argument1: method name
#c Argument2: argument modifiers (e.g. [in])
#c Argument3: argument type
#c Argument4: argument name
#c Argument5: argument comment
#c Argument6: argument modifiers (e.g. [in])
#c Argument7: argument type
#c Argument8: argument name
#c Argument9: argument comment
#c Argument10: method description
#c
#startm AD_METHOD2 10
  //****************
  // %01()
  //
  virtual AAFRESULT STDMETHODCALLTYPE
    %01
       (%03 %04,    //@parm %02 %05
        %07 %08);   //@parm %06 %09
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a method which takes three arguments.
#c
#c Argument1: method name
#c Argument2: argument modifiers (e.g. [in])
#c Argument3: argument type
#c Argument4: argument name
#c Argument5: argument comment
#c Argument6: argument modifiers (e.g. [in])
#c Argument7: argument type
#c Argument8: argument name
#c Argument9: argument comment
#c Argument10: argument modifiers (e.g. [in])
#c Argument11: argument type
#c Argument12: argument name
#c Argument13: argument comment
#c Argument14: method description
#c
#startm AD_METHOD3 14
  //****************
  // %01()
  //
  virtual AAFRESULT STDMETHODCALLTYPE
    %01
       (%03 %04,    //@parm %02 %05,
        %07 %08,    //@parm %06 %09,
        %11 %12);   //@parm %10 %13
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a method which takes four arguments.
#c
#c Argument1: method name
#c Argument2: argument modifiers (e.g. [in])
#c Argument3: argument type
#c Argument4: argument name
#c Argument5: argument comment
#c Argument6: argument modifiers (e.g. [in])
#c Argument7: argument type
#c Argument8: argument name
#c Argument9: argument comment
#c Argument10: argument modifiers (e.g. [in])
#c Argument11: argument type
#c Argument12: argument name
#c Argument13: argument comment
#c Argument14: argument modifiers (e.g. [in])
#c Argument15: argument type
#c Argument16: argument name
#c Argument17: argument comment
#c Argument18: method description
#c
#startm AD_METHOD4 18
  //****************
  // %01()
  // 
  virtual AAFRESULT STDMETHODCALLTYPE
    %01
       (%03 %04,    //@parm %02 %05
        %07 %08,    //@parm %06 %09
        %11 %12,    //@parm %10 %13
        %15 %16);   //@parm %14 %17
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a method which takes five arguments.
#c
#c Argument1: method name
#c Argument2: argument modifiers (e.g. [in])
#c Argument3: argument type
#c Argument4: argument name
#c Argument5: argument comment
#c Argument6: argument modifiers (e.g. [in])
#c Argument7: argument type
#c Argument8: argument name
#c Argument9: argument comment
#c Argument10: argument modifiers (e.g. [in])
#c Argument11: argument type
#c Argument12: argument name
#c Argument13: argument comment
#c Argument14: argument modifiers (e.g. [in])
#c Argument15: argument type
#c Argument16: argument name
#c Argument17: argument comment
#c Argument18: argument modifiers (e.g. [in])
#c Argument19: argument type
#c Argument20: argument name
#c Argument21: argument comment
#c Argument22: method description
#c
#startm AD_METHOD5 22
  //****************
  // %01()
  //
  virtual AAFRESULT STDMETHODCALLTYPE
    %01
       (%03 %04,    //@parm %02 %05
        %07 %08,    //@parm %06 %09
        %11 %12,    //@parm %10 %13
        %15 %16,    //@parm %14 %17
        %19 %20);   //@parm %18 %21
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a method which takes six arguments.
#c
#c Argument1: method name
#c Argument2: argument modifiers (e.g. [in])
#c Argument3: argument type
#c Argument4: argument name
#c Argument5: argument comment
#c Argument6: argument modifiers (e.g. [in])
#c Argument7: argument type
#c Argument8: argument name
#c Argument9: argument comment
#c Argument10: argument modifiers (e.g. [in])
#c Argument11: argument type
#c Argument12: argument name
#c Argument13: argument comment
#c Argument14: argument modifiers (e.g. [in])
#c Argument15: argument type
#c Argument16: argument name
#c Argument17: argument comment
#c Argument18: argument modifiers (e.g. [in])
#c Argument19: argument type
#c Argument20: argument name
#c Argument21: argument comment
#c Argument22: argument modifiers (e.g. [in])
#c Argument23: argument type
#c Argument24: argument name
#c Argument25: argument comment
#c Argument26: method description
#c
#startm AD_METHOD6 26
  //****************
  // %01()
  //
  virtual AAFRESULT STDMETHODCALLTYPE
    %01
       (%03 %04,    //@parm %02 %05
        %07 %08,    //@parm %06 %09
        %11 %12,    //@parm %10 %13
        %15 %16,    //@parm %14 %17
        %19 %20,    //@parm %18 %21
        %23 %24);   //@parm %22 %25
#endm

#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a method which takes seven arguments.
#c
#c Argument1: method name
#c Argument2: argument modifiers (e.g. [in])
#c Argument3: argument type
#c Argument4: argument name
#c Argument5: argument comment
#c Argument6: argument modifiers (e.g. [in])
#c Argument7: argument type
#c Argument8: argument name
#c Argument9: argument comment
#c Argument10: argument modifiers (e.g. [in])
#c Argument11: argument type
#c Argument12: argument name
#c Argument13: argument comment
#c Argument14: argument modifiers (e.g. [in])
#c Argument15: argument type
#c Argument16: argument name
#c Argument17: argument comment
#c Argument18: argument modifiers (e.g. [in])
#c Argument19: argument type
#c Argument20: argument name
#c Argument21: argument comment
#c Argument22: argument modifiers (e.g. [in])
#c Argument23: argument type
#c Argument24: argument name
#c Argument25: argument comment
#c Argument26: argument modifiers (e.g. [in])
#c Argument27: argument type
#c Argument28: argument name
#c Argument29: argument comment
#c Argument30: method description
#c
#startm AD_METHOD7 30
  //****************
  // %01()
  //
  virtual AAFRESULT STDMETHODCALLTYPE
    %01
       (%03 %04,    //@parm %02 %05
        %07 %08,    //@parm %06 %09
        %11 %12,    //@parm %10 %13
        %15 %16,    //@parm %14 %17
        %19 %20,    //@parm %18 %21
        %23 %24,    //@parm %22 %25
        %27 %28);   //@parm %26 %29
#endm

#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a method which takes eight arguments.
#c
#c Argument1: method name
#c Argument2: argument modifiers (e.g. [in])
#c Argument3: argument type
#c Argument4: argument name
#c Argument5: argument comment
#c Argument6: argument modifiers (e.g. [in])
#c Argument7: argument type
#c Argument8: argument name
#c Argument9: argument comment
#c Argument10: argument modifiers (e.g. [in])
#c Argument11: argument type
#c Argument12: argument name
#c Argument13: argument comment
#c Argument14: argument modifiers (e.g. [in])
#c Argument15: argument type
#c Argument16: argument name
#c Argument17: argument comment
#c Argument18: argument modifiers (e.g. [in])
#c Argument19: argument type
#c Argument20: argument name
#c Argument21: argument comment
#c Argument22: argument modifiers (e.g. [in])
#c Argument23: argument type
#c Argument24: argument name
#c Argument25: argument comment
#c Argument26: argument modifiers (e.g. [in])
#c Argument27: argument type
#c Argument28: argument name
#c Argument29: argument comment
#c Argument30: argument modifiers (e.g. [in])
#c Argument31: argument type
#c Argument32: argument name
#c Argument33: argument comment
#c Argument34: method description
#c
#c TomR:980713: Added
#c
#startm AD_METHOD8 34
  //****************
  // %01()
  //
  virtual AAFRESULT STDMETHODCALLTYPE
    %01
       (%03 %04,    //@parm %02 %05
        %07 %08,    //@parm %06 %09
        %11 %12,    //@parm %10 %13
        %15 %16,    //@parm %14 %17
        %19 %20,    //@parm %18 %21
        %23 %24,    //@parm %22 %25
        %27 %28,    //@parm %26 %29
        %31 %32);   //@parm %30 %33
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a method which takes nine arguments.
#c
#c Argument1: method name
#c Argument2: argument modifiers (e.g. [in])
#c Argument3: argument type
#c Argument4: argument name
#c Argument5: argument comment
#c Argument6: argument modifiers (e.g. [in])
#c Argument7: argument type
#c Argument8: argument name
#c Argument9: argument comment
#c Argument10: argument modifiers (e.g. [in])
#c Argument11: argument type
#c Argument12: argument name
#c Argument13: argument comment
#c Argument14: argument modifiers (e.g. [in])
#c Argument15: argument type
#c Argument16: argument name
#c Argument17: argument comment
#c Argument18: argument modifiers (e.g. [in])
#c Argument19: argument type
#c Argument20: argument name
#c Argument21: argument comment
#c Argument22: argument modifiers (e.g. [in])
#c Argument23: argument type
#c Argument24: argument name
#c Argument25: argument comment
#c Argument26: argument modifiers (e.g. [in])
#c Argument27: argument type
#c Argument28: argument name
#c Argument29: argument comment
#c Argument30: argument modifiers (e.g. [in])
#c Argument31: argument type
#c Argument32: argument name
#c Argument33: argument comment
#c Argument34: argument modifiers (e.g. [in])
#c Argument35: argument type
#c Argument36: argument name
#c Argument37: argument comment
#c Argument38: method description
#c
#startm AD_METHOD9 38
  //****************
  // %01()
  //
  virtual AAFRESULT STDMETHODCALLTYPE
    %01
       (%03 %04,    //@parm %02 %05
        %07 %08,    //@parm %06 %09
        %11 %12,    //@parm %10 %13
        %15 %16,    //@parm %14 %17
        %19 %20,    //@parm %18 %21
        %23 %24,    //@parm %22 %25
        %27 %28,    //@parm %26 %29
        %31 %32,    //@parm %30 %33
        %35 %36);   //@parm %34 %37
#endm

#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a method which takes ten arguments.
#c
#c Argument1: method name
#c Argument2: argument modifiers (e.g. [in])
#c Argument3: argument type
#c Argument4: argument name
#c Argument5: argument comment
#c Argument6: argument modifiers (e.g. [in])
#c Argument7: argument type
#c Argument8: argument name
#c Argument9: argument comment
#c Argument10: argument modifiers (e.g. [in])
#c Argument11: argument type
#c Argument12: argument name
#c Argument13: argument comment
#c Argument14: argument modifiers (e.g. [in])
#c Argument15: argument type
#c Argument16: argument name
#c Argument17: argument comment
#c Argument18: argument modifiers (e.g. [in])
#c Argument19: argument type
#c Argument20: argument name
#c Argument21: argument comment
#c Argument22: argument modifiers (e.g. [in])
#c Argument23: argument type
#c Argument24: argument name
#c Argument25: argument comment
#c Argument26: argument modifiers (e.g. [in])
#c Argument27: argument type
#c Argument28: argument name
#c Argument29: argument comment
#c Argument30: argument modifiers (e.g. [in])
#c Argument31: argument type
#c Argument32: argument name
#c Argument33: argument comment
#c Argument34: argument modifiers (e.g. [in])
#c Argument35: argument type
#c Argument36: argument name
#c Argument37: argument comment
#c Argument38: argument modifiers (e.g. [in])
#c Argument39: argument type
#c Argument40: argument name
#c Argument41: argument comment
#c Argument42: method description
#c
#startm AD_METHOD_10 42
  //****************
  // %01()
  //
  virtual AAFRESULT STDMETHODCALLTYPE
    %01
       (%03 %04,    //@parm %02 %05
        %07 %08,    //@parm %06 %09
        %11 %12,    //@parm %10 %13
        %15 %16,    //@parm %14 %17
        %19 %20,    //@parm %18 %21
        %23 %24,    //@parm %22 %25
        %27 %28,    //@parm %26 %29
        %31 %32,    //@parm %30 %33
        %35 %36,    //@parm %34 %37
        %39 %40);   //@parm %38 %41
#endm

#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a method which takes eleven arguments.
#c
#c Argument1: method name
#c Argument2: argument modifiers (e.g. [in])
#c Argument3: argument type
#c Argument4: argument name
#c Argument5: argument comment
#c Argument6: argument modifiers (e.g. [in])
#c Argument7: argument type
#c Argument8: argument name
#c Argument9: argument comment
#c Argument10: argument modifiers (e.g. [in])
#c Argument11: argument type
#c Argument12: argument name
#c Argument13: argument comment
#c Argument14: argument modifiers (e.g. [in])
#c Argument15: argument type
#c Argument16: argument name
#c Argument17: argument comment
#c Argument18: argument modifiers (e.g. [in])
#c Argument19: argument type
#c Argument20: argument name
#c Argument21: argument comment
#c Argument22: argument modifiers (e.g. [in])
#c Argument23: argument type
#c Argument24: argument name
#c Argument25: argument comment
#c Argument26: argument modifiers (e.g. [in])
#c Argument27: argument type
#c Argument28: argument name
#c Argument29: argument comment
#c Argument30: argument modifiers (e.g. [in])
#c Argument31: argument type
#c Argument32: argument name
#c Argument33: argument comment
#c Argument34: argument modifiers (e.g. [in])
#c Argument35: argument type
#c Argument36: argument name
#c Argument37: argument comment
#c Argument38: argument modifiers (e.g. [in])
#c Argument39: argument type
#c Argument40: argument name
#c Argument41: argument comment
#c Argument42: argument modifiers (e.g. [in])
#c Argument43: argument type
#c Argument44: argument name
#c Argument45: argument comment
#c Argument46: method description
#c
#startm AD_METHOD_11 46
  //****************
  // %01()
  //
  virtual AAFRESULT STDMETHODCALLTYPE
    %01
       (%03 %04,    //@parm %02 %05
        %07 %08,    //@parm %06 %09
        %11 %12,    //@parm %10 %13
        %15 %16,    //@parm %14 %17
        %19 %20,    //@parm %18 %21
        %23 %24,    //@parm %22 %25
        %27 %28,    //@parm %26 %29
        %31 %32,    //@parm %30 %33
        %35 %36,    //@parm %34 %37
        %39 %40,    //@parm %38 %41
        %43 %44);   //@parm %42 %45
#endm

#ccccccccccccccccccccccccccc
#c
#c Ends a class definition
#c
#c Arguments: none
#c
#startm AD_CLASS_END 00
};

#endif // ! _Impl.this-module_h_
#endm


#ccccccccccccccccccccccccccc
#c
#c Ends a class definition for AAFObject
#c
#c Arguments: none
#c
#startm AD_ROOT_CLASS_END 00
public:

  void InitComParent (I.this-module * pComParent);

  void InitCppParent (.this-module * pCppParent);

  I.this-module * GetCOMParent ();

  .this-module * GetCppParent ();

private:

  I.this-module * _pComParent;

  .this-module * _pCppParent;

};

#endif // ! _Impl.this-module_h_
#endm


#ccccccccccccccccccccccccccc
#c
#c Specifies an overridden method
#c
#c Argument: method declaration
#c
#startm AD_OVERRIDE 01
%01
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a constructor which takes one argument.
#c Constructor name is assumed to be Impl.this-module.
#c
#c Argument1: argument modifiers (e.g. [in])
#c Argument2: argument type
#c Argument3: argument name
#c Argument4: argument comment
#c Argument5: constructor description
#c
#startm AD_CONSTRUCTOR1 05
  //****************
  // constructor
  //
  Impl.this-module
        (%02 %03);  //@parm %01 %04
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a constructor which takes two arguments.
#c Constructor name is assumed to be Impl.this-module.
#c
#c Argument1: argument modifiers (e.g. [in])
#c Argument2: argument1 type
#c Argument3: argument1 name
#c Argument4: argument1 comment
#c Argument5: argument modifiers (e.g. [in])
#c Argument6: argument2 type
#c Argument7: argument2 name
#c Argument8: argument2 comment
#c Argument9: constructor description
#c
#startm AD_CONSTRUCTOR2 09
  //****************
  // constructor
  //
    Impl.this-module
       (%02 %03,    //@parm %01 %04
        %06 %07);   //@parm %05 %08
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a constructor which takes three arguments.
#c Constructor name is assumed to be .this-module.
#c
#c Argument1: argument1 modifiers (e.g. [in])
#c Argument2: argument1 type
#c Argument3: argument1 name
#c Argument4: argument1 comment
#c Argument5: argument2 modifiers (e.g. [in])
#c Argument6: argument2 type
#c Argument7: argument2 name
#c Argument8: argument2 comment
#c Argument9: argument3 modifiers (e.g. [in])
#c Argument10: argument3 type
#c Argument11: argument3 name
#c Argument12: argument3 comment
#c Argument13: constructor description
#c
#startm AD_CONSTRUCTOR3 13
  //****************
  // constructor
  //
    Impl.this-module
       (%02 %03,    //@parm %01 %04
        %06 %07,    //@parm %05 %08
        %10 %11);   //@parm %09 %12
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a constructor which takes four arguments.
#c Constructor name is assumed to be .this-module.
#c
#c Argument1: argument1 modifiers (e.g. [in])
#c Argument2: argument1 type
#c Argument3: argument1 name
#c Argument4: argument1 comment
#c Argument5: argument2 modifiers (e.g. [in])
#c Argument6: argument2 type
#c Argument7: argument2 name
#c Argument8: argument2 comment
#c Argument9: argument3 modifiers (e.g. [in])
#c Argument10: argument3 type
#c Argument11: argument3 name
#c Argument12: argument3 comment
#c Argument13: argument4 modifiers (e.g. [in])
#c Argument14: argument4 type
#c Argument15: argument4 name
#c Argument16: argument4 comment
#c Argument17: constructor description
#c
#startm AD_CONSTRUCTOR4 17
  //****************
  // constructor
  //
    Impl.this-module
       (%02 %03,    //@parm %01 %04
        %06 %07,    //@parm %05 %08
        %10 %11,    //@parm %09 %12
        %14 %15);   //@parm %13 %16
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a method which takes one argument, which is
#c a pointer to an AAF object which is to be returned to the caller.
#c This is different from the normal METHOD macro because the
#c _rep will probably have the object in a different form.
#c
#c Argument1: method name
#c Argument2: argument modifiers (e.g. [in])
#c Argument3: argument type
#c Argument4: argument name
#c Argument5: argument comment
#c Argument6: method description
#c
#startm AD_GETOBJ_METHOD1 06
  //****************
  // %01()
  //
  virtual AAFRESULT STDMETHODCALLTYPE
    %01
        (Impl%03 ** %04);   //@parm %02 %05
#endm


#ccccccccccccccccccccccccccc
#c
#c Inserts declaration for a method which takes one argument, which is
#c a pointer to an AAF object which is to be passed in from the caller.
#c This is different from the normal METHOD macro because the
#c _rep will probably have the object in a different form.
#c
#c Argument1: method name
#c Argument2: argument modifiers (e.g. [in])
#c Argument3: argument type
#c Argument4: argument name
#c Argument5: argument comment
#c Argument6: method description
#c
#startm AD_SETOBJ_METHOD1 06
  //****************
  // %01()
  //
  virtual AAFRESULT STDMETHODCALLTYPE
    %01
        (Impl%03 * %04);    //@parm %02 %05
#endm
